BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXXXXXXXXX XX X XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX X
        XXXXXXXXXXX XX X XXXXXXXXXXXXX XX XXXXXXX XX X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB
            BBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
        BBBBB
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXFFFFFFFXXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXX
                        BB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXBBBBB
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX
                                XXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBB
                                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                        BBB BBBBBBB BB BBBBBBBB
                                            XXX XXXXXXXXXXXXXXXXXXXXX
                                                XX XXXXXXBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                                            BB BBBBBBBBBBB
                                                                BBBBB BBBBBBBBBBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                                                                XXXX XXXXXX XXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                                            BBBB
                                                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                                            BBBBB
                                                        BBBBBBB
                                                    XXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX
                                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXX
                                                    XXXX XXXXXXXXXXXXXXXXXXXXX
                                                        
                                                        
                                                        
                                                        XXXXX XXXXXXXXXXXXXXXXXXXXXX
                                                            XX XXXXXXXXXX XXXXXXXXXXXX 
                                                        XXXXXXX
                                                        XXXXX XXXXXXXXXXXXXXXXXXXXX
                                                            XX XXXXXXXXXX XXXXXXXXXXXXXX FFFFFFFFFFFF
                                                        XXXXXXX
                                                    XXXXXX
                                                XXXX
                                            XXXXX
                                        BBBBBB
                                    XXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
                                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB
                                    BBBBB
                                BBBB
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                                BBBBB
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBXXXX XXXXXX XXXXX XXXXXXBBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                             XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXX XXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXX XXX XXXXXXXXXBBBBXXXXXXXXX XXX XXXXXXXXXBBBBBXX
                                    XX XXXXXXXBB BBBBBBBBBBBBXXX XXXXXXXXXXXBBBBXXX XXXXXXXXXXXBBBBBXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXXXBBBBXXXXXXXXXBBBBBXXXXXXX
                                XXXXXXXXX
                            BBBB
                                 XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFF FFFFFFFFFFXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX
                        XXXXXX
                    XXXXXX
                XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
XXXXXX

XXXXX XXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBXXXXXXX
BBBBBBBB

BBBBB BBBBBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXX X XXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX

            XXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XX
            XX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXX XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX X XXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX X
                XXXXXX XXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXX XX X
                XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X XX
                
                XX XXXXXXXXXXXX XXX XXXXXXX XX XXXXXXXXXXXXXXXXX XXX XXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX X XX
                X XXXX XX XXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXXXX XXX XXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX X XX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X 
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXX 
                XXXXXXXXXXXX X X XXXXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX 
            XX
            XXXXXXXXXXX XX X 
                XXXXXXXXXXXXX X XXXXXX 
            XXX
        XXX
    X
    
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXX
        XXX
    X
XXX
XXXXXXXXX
BBBBBBBB