BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB 

BBBBB BBBBB
    BB BBBBBBB BB BBBBBBBBB
         gettext(u'Conectar %(provider_name)s') SSSSSSSS SSSSSSSSSSSSSSSSS
    BBBB
         gettext(u'Confirmar Login com %(provider_name)s') SSSSSSSSS SSSSS SSS SSSSSSSSSSSSSSSSS 
    BBBBB
    X 
BBBBBBBB BBBBB

BBBBB BBBBBBBBB
    
    
    
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 

        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBB
                XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFF XXXXX XXXXXXXXXXXXXXXXXXXXXXXX 
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXXXXXXX
            BBBBB

            BB BBBBBBB BB BBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Conectar conta %(provider_name)s') SSSSSSSS SSSSS SSSSSSSSSSSSSSSSSXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Continuar com %(provider_name)s') SSSSSSSSS SSS SSSSSSSSSSSSSSSSSXXXXX
            BBBBB
        XXXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
        BB BBBBBBB BB BBBBBBBBB
             gettext(u'Você está prestes a conectar sua conta %(provider_name)s à sua conta AstraToons existente.') SSSS SSSS SSSSSSS S SSSSSSSS SSS SSSSS SSSSSSSSSSSSSSSSS S SSS SSSSS SSSSSSSSSS SSSSSSSSSS
        BBBB
             gettext(u'Confirme para usar sua conta %(provider_name)s para acessar o AstraToons.') SSSSSSSS SSSS SSSS SSS SSSSS SSSSSSSSSSSSSSSSS SSSS SSSSSSS S SSSSSSSSSSS
        BBBBB
        XXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX 
                
                 gettext(u'Continuar') 
            XXXXXXXXX
            
            XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX gettext(u'Cancelar') XXXX
        XXXXXXX

        
        BB BBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                BBBBBBBBBB
                BBB BBBBB BB BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBB
                        BB BBBBBBBBBBBB
                            XXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXX
                        BBBBB
                    XXXXXX
                BBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Salvar e Continuar') XXXXXXXXX
                XXXXXX
            XXXXXXX
        BBBBB

    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB