BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Sair da Conta') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    
BBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX gettext(u'Sair da conta') XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
                 gettext(u'Tem certeza que deseja deslogar da sua conta?') SSS SSSSSSS SSS SSSSSS SSSSSSSS SS SSS SSSSSS
            XXXX
            XXX
                 gettext(u'Você precisará fazer login novamente para acessar seus favoritos e histórico.') SSSS SSSSSSSSS SSSSS SSSSS SSSSSSSSS SSSS SSSSSSS SSSS SSSSSSSSS S SSSSSSSSSS
            XXXX
        XXXXXX

        
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
            BBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                
                
                XX XXXXXXFFFFFFFFFFFX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                     XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'Cancelar') 
                XXXX

                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Sim, sair') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX

    XXXXXX 
XXXXXXX
BBBBBBBB BBBBBBB


BBBBB BBBBBBBB
XXXXXXXX
    XX XXXXXXXX XX XXXXXXXX XXXXXX XX XXXXXXXXX XX XXXXX XX XXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXX XX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXX X XXXXX X XXXXXXXX XXXXX XX XXXX XX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXX
    X

    XX X XX XX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX XXXX XXXXX X XXXX XXXXXXXXXX
    XX XXXXX XXXXXX X XXXXXX XXXXXXXX XX XXX XXXX X XXXXX
XXXXXXXXX
BBBBBBBB