BBBBBBB BBBBBBBBBBB 
BBBB BBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB 

BBBBB BBBBB gettext(u'Login')  X BBBBBBBB

BBBBB BBBBBBBBB
     
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Fechar') XX
                XX XXXXXXXXXX XXXXXXXXXXXXXX 
            XXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB 
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFF XXXXXX
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            BBBBB

            XXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Faça login na sua conta') XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Acesse para salvar seus mangás favoritos e receber recomendações.') XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
                BBBBBBBBBB

                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                            XXXXXXX
                        BBBBBB
                    XXXXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
                BBBBB

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Usuário ou E-mail') XXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Senha') XXXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX

                BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XXXXXX XXXXXXX gettext(u'Lembrar de mim') XXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBB

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Entrar') XXXXXXXXX
                XXXXXX

            XXXXXXX 

            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX gettext(u'Ou conecte-se com') XXXXX
                XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX gettext(u'Login com Discord') XXXXXXX
                XXXX
            XXXXXX
            

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Não tem conta?')  XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Cadastre-se') XXXX
            XXXX
        XXXXXX 
    XXXXXX 
XXXXXX 
BBBBBBBB BBBBBBB