 #

BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Email Enviado') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXX XXXX X XXXXXXXXXXXX XXXX XXXXXXXXXXX X XXXXXXXX 
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Verifique seu Email') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Enviamos um email com instruções para definir sua senha, **se uma conta existir com o email que você digitou**. Você deve recebê-lo em breve.') SSSSSSSS SS SSSSS SSS SSSSSSSSSS SSSS SSSSSSS SSS SSSSSS SSSS SSS SSSSS SSSSSSS SSS S SSSSS SSS SSSS SSSSSSSSSS SSSS SSSS SSSSSSSSS SS SSSSSS
                    XXXX
                     XX XXXXXXXXXXXXXXXXXXXX XXXXXX
                        gettext(u'Se você não receber um email, por favor, certifique-se de que digitou o endereço com o qual se registrou e verifique sua pasta de spam.') SS SSSS SSS SSSSSSS SS SSSSSS SSS SSSSSS SSSSSSSSSSSSS SS SSS SSSSSSS S SSSSSSSS SSS S SSSS SS SSSSSSSSS S SSSSSSSSS SSS SSSSS SS SSSSS
                    XXXX
                    XXXX XXXXXXXXXXXXX
                         XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Voltar para Home') XXXX 
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB