 #

BBBBBBBBBB BBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXXXX XX XXXXX X BBBBBBBBXXXXXXXX 
    XXXXXXX
        XXXX X XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXX XX XXXXXXX XXXXXX XX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XX X
        XXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX X
        XX X XXXXXX XXXXXXXX XXXXXXXXXX XXXXX X
        X X XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXXX
        X X XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX X
        XXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXX X XX XXXXXX XXXXXX XX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXX XX XXXX XX XXXXXXX XX XXXXX XX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXX XX XXXX XXXXXXX XXXXX XX
            XXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXX XXXX XX X
        XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX X XX XXXX XXXXXXX XXXXX XXXXXX XX
        XXXXXXX X XXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX X
        XXXXXXXXX X XXXXXXXXXXXX XXXXX X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXBB BBBBBBBBBBBBBBBBBBX BBBBBXXXXXX 

        XXX gettext(u'Você (ou alguém se passando por você) solicitou uma redefinição de senha para sua conta em %(site_name)s.') SSSS SSS SSSSSS SS SSSSSSSS SSS SSSSS SSSSSSSSS SSS SSSSSSSSSSS SS SSSSS SSSS SSS SSSSS SS SSSSSSSSSSSSSSXXXX

        XXX gettext(u'Por favor, clique no botão abaixo para definir uma nova senha:') SSS SSSSSS SSSSSS SS SSSSS SSSSSS SSSS SSSSSSS SSS SSSS SSSSSSXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Definir Nova Senha') 
            XXXX
        XXXXXX

        XXX gettext(u'Se o botão não funcionar, copie e cole o seguinte link no seu navegador:') SS S SSSSS SSS SSSSSSSSSS SSSSS S SSSS S SSSSSSSS SSSS SS SSS SSSSSSSSSSXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBXXXX
        XXXXXX

        XX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Se você não solicitou esta redefinição, pode ignorar este e-mail com segurança. Sua senha não será alterada.') SS SSSS SSS SSSSSSSSS SSSS SSSSSSSSSSSS SSSS SSSSSSS SSSS SSSSSS SSS SSSSSSSSSS SSS SSSSS SSS SSSS SSSSSSSSSXXXX

        BB BBBBBBBBBBBBBBBBB 
            XXX gettext(u'Seu nome de usuário, caso tenha esquecido: <span class="username">%(user.get_username)s</span>') SSS SSSS SS SSSSSSSS SSSS SSSSS SSSSSSSSSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXX
             gettext(u'Obrigado,') SSSSSSSSSXXXX
            XXXXXX 
        XXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
BBBBBBBBBBBBB