 #

BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Definir Nova Senha') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXX XXXX X XXXXXXXXXXXX XXXX XXXXXXXXXXX X XXXXXXXX 
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB 
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Definir Nova Senha') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Por favor, insira sua nova senha duas vezes para confirmar.') XXXX
                    XXXXXX

                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB XXXXXXX BBBBBB
                        XXXXXX
                    BBBBB

                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Nova senha') XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX
                                           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Mostrar/Ocultar senha') XX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX 
                                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXFFFFXXXXBBBBB
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXXBBBBB
                            XXXXXX

                            
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Confirmar nova senha') XXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX
                                           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Mostrar/Ocultar senha de confirmação') XX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX 
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXXBBBBB
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Alterar Senha')  
                            XXXXXXXXX
                        XXXXXX
                    XXXXXXX

                BBBB 
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Link Inválido') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'O link de redefinição de senha era inválido, possivelmente porque já foi usado ou expirou. Por favor, solicite uma nova redefinição de senha.') S SSSS SS SSSSSSSSSSS SS SSSSS SSS SSSSSSSSS SSSSSSSSSSSSS SSSSSS SS SSS SSSSS SS SSSSSSSS SSS SSSSSS SSSSSSSS SSS SSSS SSSSSSSSSSS SS SSSSSS
                        XXXX
                        XXXX XXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Solicitar Novo Link') XXXX
                        XXXXXX
                    XXXXXX
                BBBBB 
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
    
    XXXXXXXX
         XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X XXXXXX X XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
            X
        X
        XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX XXX X XX XXXXXXXXXXXXXXXXXX XXX XX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXXXXX X X gettext(u'As senhas coincidem!') XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
            X XXXX XX XXXXXXXXXXXXXXXXXXXXXXX X XX X
                XXXXXXXXXXXXXXXXXXXXX X X gettext(u'As senhas não coincidem!') XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            X XXXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX X
        X
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X XX XXX XXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXX XXX XX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXX X
            XX XXXXXXXXXXXXXXXX XX XX XXXXXXXX XX XXX
            XX XXXXXXXXXXXXXXXX XX XXX XXXXXXXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
            XXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXX
            XX XXXXXXXXX X XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XX XXXXXXXXX X XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
BBBBBBBB