 #

BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Redefinir Senha') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXX XXXX X XXXXXXXXXXXX XXXX XXXXXXXXXXX X XXXXXXXX 
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Redefinir sua Senha') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Digite seu email abaixo e enviaremos instruções para criar uma nova senha.') XXXX
                XXXXXX

                 BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB XXXXXXX BBBBBB
                    XXXXXX
                BBBBB

                 
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXX XXXXX
                                       XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X 
                                       XXXXXXXFFFFFFFFFFXX
                                
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXXBBBBB
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Enviar Email de Recuperação') 
                         XXXXXXXXX
                    XXXXXX
                XXXXXXX

                 XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Voltar para o Login') XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB