 #

BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Senha Redefinida') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXX XXXX X XXXXXXXXXXXX XXXX XXXXXXXXXXX X XXXXXXXX 
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                     XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Senha Redefinida!') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX
                        gettext(u'Sua senha foi alterada com sucesso. Agora você pode fazer login com sua nova senha.') 
                    XXXX
                     XXXX XXXXXXXXXXXXX 
                         XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Ir para Login') XXXX
                     XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB