BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXXXXX XXXXX X XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX 
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

                BB BBBBBBBBB 
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXX XXXX XXXXX XXXX XXXXXXXXXX
                    XXXXXX

                    
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                                XXXXXXX
                            BBBBBB
                        XXXXXX
                    BBBBB

                    
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

                            
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                     
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                                
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXXBBBBB
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                    XX XXXXXXXXXXXXXXXXXXFFFFXXXX
                                BBBBB
                            XXXXXX

                            
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXX
                                    
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                                
                                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXXBBBBB
                            XXXXXX

                            
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX
                                XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXX

                BBBB 
                     XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                         XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                             XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         XXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                            X XXXX XX XXXXXXXXXXX XX XXXXX XXX XXXX XXXX X XXXXXXXX XX XX XXXXXXXX
                            XXXX XXXX XXXXXXXXX XX XXX XX XXX XXXXX XX XX XXXX XXXXXX XXXXXXXXXXXXXX X XXXX
                        XXXX
                         XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                            XXX XXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XX XXXX XXXXXXXXX
                        XXXX
                    XXXXXX
                BBBBB 

            XXXXXX 
        XXXXXX 
    XXXXXX 
XXXXXX 
BBBBBBBB

BBBBB BBBBBBBB

XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X XXXXXX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        X
    X

     XX XXXXXXXX XXXXX XXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX

        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXX XXX X XX XXXXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX XXXX XXX XXXXXXX XXXX
        XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX X XXX XXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXX XXXXXXX XXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXX X XXX XXXXXX XXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXX XXXXXXXXXX XXXXX
        X
    X

     XX XXXXXXXX XXXXXXXX XXXXXXXXX
     XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX

        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XX
        XXX XXXXXXXX X XXXXXXX XX XXXXXXX XXX XXXXX

        XX XXXXXXXXXXXXXXXX XX XX XXXXXXXX XX XXX XXXX XXXXXXXX X XXXXXXXXXXX XXXXXXXX X XXXX
        XX XXXXXXXXXXXXXXXX XX XXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXX

        XXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX XXXXX XXXXXXX X XXX XXX

        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXX

        XX XXXXXXXXX X XXX X
            XXXXXXXX X XXXXXXXXXX XX XXX
        X XXXX XX XXXXXXXXX X XXX X
            XXXXXXXX X XXXXXXXXXX XX XXXXXXXXXXXXX
        X XXXX X
            XXXXXXXX X XXXXXXXXXX XX XXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
    X


    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

        XX XXX XXXXXXXXX XXX XXXXXXXX XXX XXXXX XXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXX XXXX XXXXXX XXX XXXX
        X
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXXX XXXXXX XX XXXXXX XXXX XXXXXX XXXXXX XXXXX XXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
    XXX
XXXXXXXXX
BBBBBBBB