BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Cadastrar')  X BBBBBBBB

BBBBB BBBBBBBBB
    
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFF XXXXXX
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXXXXXXX
            BBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Crie sua conta') XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Insira seus dados abaixo para criar uma nova conta.') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
                BBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBBXXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Nome de usuário') XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Endereço de e-mail') XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Senha') XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX

                BB BBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Confirme a senha') XXXXXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXXBBBBB
                XXXXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Cadastrar') XXXXXXXXXXXXXXX
            XXXXXXX

            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX gettext(u'Ou registre-se com') XXXXX
                XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX gettext(u'Registrar com Discord') XXXXXXX
                XXXX
            XXXXXX
            

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Já é um usuário?')  XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Faça login agora') XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB