BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Verifique seu E-mail') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    
    
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 

             
             BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXX
                         
                    XXXXXX
                    BBBBBB
                XXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX

            XXXX gettext(u'Confirmação de Email Enviada!') XXXXX

            XXX
                
                 gettext(u'Nós enviamos um link de confirmação para o seu endereço de e-mail.\n                Por favor, verifique sua caixa de entrada (e spam) e clique no link para ativar sua conta.') SSS SSSSSSSS SS SSSS SS SSSSSSSSSSS SSSS S SSS SSSSSSSS SS SSSSSSS
                SSS SSSSSS SSSSSSSSS SSS SSSSS SS SSSSSSS SS SSSSS S SSSSSS SS SSSS SSSS SSSSSS SSS SSSSSS
            XXXX

            
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Não recebeu o email? Verifique sua pasta de spam ou <a href="%(resend_url|default:\'#\')s" id="resendLink">reenvie a confirmação</a>.') SSS SSSSSSS S SSSSSS SSSSSSSSS SSS SSSSS SS SSSS SS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSS S SSSSSSSSSSSSSSSS
                     #

                XXXX
                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    gettext(u'Você pode solicitar um novo email em')  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'segundos') 
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX 
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Ir para Login') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXXX
BBBBBBBB BBBBBBB


BBBBB BBBBBBBB
XXXXXXXX
    XX XXXXXX XXXX X XXXX XX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXX X XXX

    XX XXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X
            XX XXX XXXX XXXX XX XXXXXXX XXXXXXXXXXXX XXXXX XXX
            XXXXXXXXXXXXXXXXXXX XX XXXXXXX X XXXX XXXXXXX XXX XXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX
            XX XXX XXX XXXXXXXXX XXX
        XXX
    X

    XXXXXXXX XXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XX XXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX XXXXXX
    X
XXXXXXXXX
BBBBBBBB