BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXXX X XXXX XXXX XXXXXX XXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXX XXX XX XXXXX XXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
        X
        XXXXXX XXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX X X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX X

        XX XXX XXXX XXXXXXXX XXX XX XXXXX XXXXXXXX X X XXXXXX XXXXX XXXXXXX XX
        XXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXXXXXX XXXXXXXXXXXX X XXXXXXXX X XXXXX X
        XXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXX X XXXXXX X
        XXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXX XXX XXXXXX XXXXX XXXXXXX XXXXX X
        XXXXXXXXXXX X XXXXX XXXXXX X
        XXXXXXXXXXX X XXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXX XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX X
    XXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX XXXX XX XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX X XXXXXXXXX XXXX XXXXXX X XXXXXXXXXX XX XXX XXX XXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXXXX XXXX XXXXX
    XXXXXXXXX XXXXX XXX XXXXXX XXX XXX X X XXXXXXX XXXXXX X XXXXX X XXXXXX X XXXX XXXX XXXXX XX XXXXXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
                    XXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXX
                    XXXXXXXXXXXXX XX XXXXXX XXXXXXXXX
                    XXX XXXXXXXXX XXX XXXXXXX XXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    BBBBB

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX
                     XX XXXXXXX XXXXXXXXXXXXXXXXXXX
                         XXXX XXXXXXXXXXXXXXXXXXXXXX
                            BBBBB BBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BB BBBBBBBBB
                            XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                                 XXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                 XXXXXX
                            XXXXXX
                        XXXXXX
                     XXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                        XXXXFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFF FFFFFFFFFFFXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFFF FFFFFF X
                        XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXFFFFFFFFFFFFFFFFFF FFFFFFFFXXXXX
                        XXXX
                            BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXX
                                    BB BBBBBBBBBBBB BB BBBBBBBBBBBXX XXXXXXXXXX XXXXXXXXXXXXX
                                    BBBB BBBBBBBBBBBB BB BBBBBBBXX XXXXXXXXXX XXXXXXXXXXXXXX
                                    BBBB BBBBBBBBBBBB BB BBBBBBXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                    BBBBXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB
                                    
                                XXXXX
                            BBBBB
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX X XXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                            BBBBBB
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    BBBBB

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBBBB
            XXXXXX
            BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX
                BB BBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                BBBBB
            BBBB
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB
            XXXXXX
            BB BBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        BB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBB BB BBBBBBBBBBBBXXXX XXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        BBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX
                                             BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB
                                        XXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBB BBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXBBBBB
                                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XXXXXX
                                XXXX
                            XXXXXX
                        XXXXXX
                    BBBBB
                         XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                    BBBBBB
                XXXXXX
            BBBB
                XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFBBBBXXXXXX XXXXXX XXX XXXXX X XXXXXX X XXXX XXXXXXXXXXXX XXXXXX XXXXXX XX XXXXXXXX X XXXXXXXXX XXXX XX XXXXXX XXXX XXXXXXXXX X XXXXXXXXX XXXX XXXX X XXXXXXXXXXXXXXXBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXX XXXX XXXXXXXBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXX XXXX XXXXXXXBBBBB
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
    XXXXXXXXXX
    BBBBB

XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
   

   XXXX XXXXXX X XXXXX XXXXXXXX XX XXXXXXXX XXXXXXXXXXX XXXXX XXX
   XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
      XX XXXXXXX XXXX X XXXXXX XX XX XXXXXXXX XX XXXXXX XXXX XXXXXXXX XXX XXX XXXX XXXX X XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXX XXX XXXXXXXXXX XXXXXXXXXX X XXXXXX
        XXX X
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXXXXX X XXX
                XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
                    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXX X XXXXXXXXXXXXX X X X XX
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXX XXXXXXXX X XXXXXXXXXXXXX X XX X XXX
                    XXXXX XXXXX X XXXXXXXXXXXXX X XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X
        X XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXX XXXXXXXXXXXXX XXXXXXX X

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XX XXX XXXXXXXX XX XXXXXX XXXXXXXXXXX XXX XXXXX XXX XX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXX
                XXXXXXXXX XXXXX
                XXXXXX XXXX
                XXXXXXXXXXXXX XX
                XXXXXXXXXXXXXXX XX
                XXXXXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXXXXXX X
                    X
                        XXXXXXXXXXX XXXXX
                        XXXXXXXXX X
                            XXXXXXXXXXXXX XX
                            XXXXXXXXXXXXXXX X
                        X
                    XX
                    X
                        XXXXXXXXXXX XXXX
                        XXXXXXXXX X
                            XXXXXXXXXXXXX XX
                            XXXXXXXXXXXXXXX XX
                            XXXXXXX XXXXX
                        X
                    X
                X
            XXX
        X XXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
        X

        XX XXXXXX XX XXXXXXXXX XXXXX XXXXXXXXXX X XXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX X
            XXX XXXXXXXXXXX X XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXX XXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXX

                XXXXXXXXXX
                    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                    XXXXXXXXXX XX X
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXX XXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        X
                        XX XXXXXXXXXXXXXXX X
                            XXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXX
                            XXXXXXXXXXXXX X XXXXXX
                        X XXXX X
                            XXXXXXXXXXXXXX
                        X
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXX XXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXX X XXXXX XX XXXXXXXXX XXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXX X XXXXXX
                    XXX
            XXX
        X
      XXX
    XXXXXXXXX
BBBBBBBB BBBBBBBB