# Generated by Django 5.1.8 on 2025-05-04 15:30

import django.db.models.deletion
import manga.models
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('chapter_number', models.CharField(db_index=True, max_length=20, verbose_name='Número/ID do Capítulo')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Capítulo VIP?')),
                ('release_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Lançamento Efetiva')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa do Capítulo (Opcional)')),
            ],
            options={
                'verbose_name': 'Página de Capítulo',
                'verbose_name_plural': 'Páginas de Capítulo',
                'ordering': ['path'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda (Opcional)')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem da Página')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_images', to='manga.mangachapterpage')),
            ],
            options={
                'verbose_name': 'Imagem de Página',
                'verbose_name_plural': 'Imagens de Páginas',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MangaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Comentário')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/%Y/%m/', verbose_name='Imagem Anexada')),
                ('is_spoiler', models.BooleanField(default=False, verbose_name='É Spoiler?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='wagtailcore.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='manga.mangacomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Mangá',
                'verbose_name_plural': 'Comentários de Mangá',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('manga_type', models.CharField(choices=[('MA', 'Manga (Japonês)'), ('MH', 'Manhwa (Coreano)'), ('MU', 'Manhua (Chinês)'), ('WT', 'Webtoon'), ('OT', 'Outro')], default='MH', max_length=2, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('OG', 'Em Andamento'), ('CP', 'Completo'), ('HT', 'Hiato'), ('CL', 'Cancelado')], default='OG', max_length=2, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor(es)')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='Artista(s)')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[manga.models.validate_rating_range], verbose_name='Nota (0.0 a 10.0)')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Sinopse')),
                ('release_day', models.CharField(blank=True, choices=[('MON', 'Segunda-feira'), ('TUE', 'Terça-feira'), ('WED', 'Quarta-feira'), ('THU', 'Quinta-feira'), ('FRI', 'Sexta-feira'), ('SAT', 'Sábado'), ('SUN', 'Domingo'), ('UND', 'Indefinido / Sem dia fixo'), ('IRR', 'Irregular')], help_text='Selecione o dia principal que novos capítulos costumam sair.', max_length=3, null=True, verbose_name='Dia da Semana (Lançamento Aprox.)')),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa')),
            ],
            options={
                'verbose_name': 'Página de Mangá',
                'verbose_name_plural': 'Páginas de Mangá',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MangaPageGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_items', to='manga.mangapage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Gênero da Obra',
                'verbose_name_plural': 'Gêneros da Obra',
            },
        ),
        migrations.AddField(
            model_name='mangapage',
            name='genre',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='manga.MangaPageGenre', to='taggit.Tag', verbose_name='Gêneros'),
        ),
    ]
