# Generated by Django 5.1.8 on 2025-05-05 23:08

import django.db.models.deletion
import manga.validator
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.AddField(
            model_name='mangapage',
            name='alternative_titles',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Títulos Alternativos'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='news_updates',
            field=wagtail.fields.RichTextField(blank=True, help_text='Use este espaço para avisos sobre hiatos, mudanças, informações extras, etc.', null=True, verbose_name='Notícias e Avisos'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='original_link_cn',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Original (Chinês)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='original_link_en',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Oficial (Inglês)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='original_link_jp',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Original (Japonês)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='original_link_kr',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Original (Coreano)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora/Plataforma'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Lançamento'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail do Capítulo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='mangacomment',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_comments', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='mangacomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_manga_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[manga.validator.validate_rating_range], verbose_name='Nota Média (0.0 a 10.0)'),
        ),
    ]
