# Generated by Django 5.1.8 on 2025-05-05 23:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_mangachapterpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('zip_file', models.FileField(upload_to='chapter_uploads/%Y/%m/', verbose_name='Arquivo ZIP')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado?')),
                ('processed_chapters', models.PositiveIntegerField(default=0, verbose_name='Capítulos Processados')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_uploads', to='manga.mangapage')),
            ],
            options={
                'verbose_name': 'Upload de Capítulos',
                'verbose_name_plural': 'Uploads de Capítulos',
                'ordering': ['-upload_date'],
                'abstract': False,
            },
        ),
    ]
