# Generated by Django 5.1.8 on 2025-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_mangachapterupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Arquivo de Imagem do Capítulo', 'verbose_name_plural': 'Arquivos de Imagem do Capítulo'},
        ),
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-release_date', '-first_published_at', 'path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.AlterModelOptions(
            name='mangachapterupload',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Upload de Capítulos (Registro)', 'verbose_name_plural': 'Uploads de Capítulos (Registros)'},
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='image',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='relative_path',
            field=models.CharField(blank=True, db_index=True, help_text='Caminho do arquivo a partir da pasta de mídia (ex: mangas/slug-obra/slug-cap/img.jpg)', max_length=500, null=True, unique=True, verbose_name='Caminho Relativo do Arquivo'),
        ),
        migrations.AlterField(
            model_name='mangachapterupload',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Status/Notas Processamento'),
        ),
        migrations.AlterField(
            model_name='mangachapterupload',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Processado?'),
        ),
        migrations.AlterField(
            model_name='mangachapterupload',
            name='processed_chapters',
            field=models.PositiveIntegerField(default=0, verbose_name='Capítulos no ZIP'),
        ),
    ]
