# Generated by Django 5.1.8 on 2025-05-06 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_chapterimage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimage',
            name='relative_path',
            field=models.CharField(blank=True, db_index=True, help_text='Caminho do arquivo a partir da pasta de mídia', max_length=500, null=True, unique=True, verbose_name='Caminho Relativo do Arquivo'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail (Opcional)'),
        ),
        migrations.AlterField(
            model_name='mangachapterupload',
            name='zip_file',
            field=models.FileField(help_text='Apenas arquivos .zip são permitidos.', upload_to='chapter_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Arquivo ZIP'),
        ),
    ]
