# Generated by Django 5.1.8 on 2025-05-06 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_chapterimage_relative_path_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': [models.OrderBy(models.F('release_date'), descending=True, nulls_last=True), models.OrderBy(models.F('first_published_at'), descending=True, nulls_last=True), models.OrderBy(models.F('chapter_number_float'), descending=True, nulls_last=True), 'path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='chapter_number',
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter_number_float',
            field=models.FloatField(blank=True, db_index=True, help_text='Ex: 105.0, 10.5, 0.0 para prólogo. Usado para ordenação correta.', null=True, verbose_name='Número para Ordenação'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter_number_str',
            field=models.CharField(db_index=True, default='', help_text="Ex: '105', '10.5', 'Extra 1', 'Prólogo'. Usado para exibição e slug.", max_length=50, verbose_name='Número/ID Texto do Capítulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangapage',
            name='custom_publish_date',
            field=models.DateTimeField(blank=True, default=None, help_text="Data para ordenação de 'lançamentos'. Se vazio, 'Última Publicação da Revisão' ou 'Primeira Publicação' será usado.", null=True, verbose_name='Data de Publicação Customizada'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número de vezes que esta página de mangá foi visualizada.', verbose_name='Contagem de Visualizações'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='release_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Lançamento Efetiva'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa'),
        ),
    ]
