# Generated by Django 5.1.8 on 2025-05-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_mangachapterpage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-release_date', '-first_published_at', 'path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='chapter_number_float',
        ),
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='chapter_number_str',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='custom_publish_date',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='views_count',
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter_number',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='Número/ID do Capítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='release_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Lançamento Efetiva'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa'),
        ),
    ]
