# Generated by Django 5.1.8 on 2025-05-07 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_mangachapterpage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Favoritado em')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='manga.mangapage', verbose_name='Mangá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-favorited_at'],
                'unique_together': {('user', 'manga')},
            },
        ),
    ]
