# Generated by Django 5.1.8 on 2025-05-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_favorite'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Imagem do Capítulo', 'verbose_name_plural': 'Imagens do Capítulo'},
        ),
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['chapter_number'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.RenameField(
            model_name='chapterimage',
            old_name='page',
            new_name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='relative_path',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título Opcional do Capítulo'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='chapter_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='Número inteiro para ordenação (ex: 1, 2, 105). Use o título para extras.', null=True, verbose_name='Número do Capítulo'),
        ),
    ]
