# Generated by Django 5.1.8 on 2025-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_alter_chapterimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Arquivo de Imagem do Capítulo', 'verbose_name_plural': 'Arquivos de Imagem do Capítulo'},
        ),
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-release_date', '-first_published_at', 'path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.RenameField(
            model_name='chapterimage',
            old_name='chapter',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='chapter_title',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='relative_path',
            field=models.CharField(blank=True, db_index=True, help_text='Caminho do arquivo a partir da pasta de mídia', max_length=500, null=True, unique=True, verbose_name='Caminho Relativo do Arquivo'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='chapter_number',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='Número/ID do Capítulo'),
            preserve_default=False,
        ),
    ]
