# Generated by Django 5.1.8 on 2025-05-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_alter_chapterimage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['chapter_number'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter_title',
            field=models.CharField(blank=True, help_text="Ex: 'O Começo', 'Volume Extra'.", max_length=255, null=True, verbose_name='Título Opcional do Capítulo'),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='chapter_number',
            field=models.FloatField(blank=True, db_index=True, help_text='Número para ordenação (ex: 1, 1.5, 10.0). Deixe em branco para capítulos especiais sem número, usando apenas o título.', null=True, verbose_name='Número do Capítulo'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail do Capítulo (Opcional)'),
        ),
    ]
