# Generated by Django 5.1.8 on 2025-05-09 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_alter_mangachapterpage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-release_date', '-first_published_at', 'path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='chapter_title',
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='chapter_number',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='Número/ID do Capítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail (Opcional)'),
        ),
    ]
