# Generated by Django 5.1.8 on 2025-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_alter_mangachapterpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='release_day',
            field=models.CharField(blank=True, choices=[('MON', 'Segunda-feira'), ('SUN', 'Domingo'), ('UND', 'Indefinido / Sem dia fixo'), ('IRR', 'Irregular')], help_text='Selecione o dia principal que novos capítulos costumam sair.', max_length=3, null=True, verbose_name='Dia da Semana (Lançamento Aprox.)'),
        ),
    ]
