# Generated by Django 5.1.8 on 2025-05-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_alter_mangapage_release_day'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail Personalizada (Opcional)'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='release_day',
            field=models.CharField(blank=True, choices=[('MON', 'Segunda-feira'), ('TUE', 'Terça-feira'), ('WED', 'Quarta-feira'), ('THU', 'Quinta-feira'), ('FRI', 'Sexta-feira'), ('SAT', 'Sábado'), ('SUN', 'Domingo'), ('UND', 'Indefinido / Sem dia fixo'), ('IRR', 'Irregular')], help_text='Selecione o dia principal que novos capítulos costumam sair.', max_length=3, null=True, verbose_name='Dia da Semana (Lançamento Aprox.)'),
        ),
    ]
