# Generated by Django 5.1.8 on 2025-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0014_alter_mangachapterpage_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='discord_series_role_id',
            field=models.CharField(blank=True, help_text='Opcional. ID do cargo do Discord a ser mencionado quando novos capítulos desta obra forem lançados.', max_length=30, null=True, verbose_name='ID do Cargo no Discord (Notificações)'),
        ),
    ]
