# Generated by Django 5.1.8 on 2025-05-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_mangapage_discord_series_role_id'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapterpage',
            name='force_show_new_badge',
            field=models.BooleanField(default=False, help_text="Se 'Sobrescrever' estiver marcado, esta opção força a exibição do badge. Usa texto/imagem global se os campos abaixo estiverem vazios.", verbose_name="Forçar Exibição do Badge 'Novo'?"),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='manual_badge_image',
            field=models.ForeignKey(blank=True, help_text='Imagem específica para o badge deste capítulo. Substitui o texto manual e a imagem global se definida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/GIF Manual do Badge (Opcional)'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='manual_badge_text',
            field=models.CharField(blank=True, help_text="Texto específico para o badge deste capítulo. Se vazio e 'Forçar Exibição' estiver marcado, usará o texto global.", max_length=20, verbose_name='Texto Manual do Badge (Opcional)'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='override_new_badge_settings',
            field=models.BooleanField(default=False, help_text="Marque para definir manualmente o status/aparência do badge 'Novo' para ESTE capítulo, ignorando as configurações globais.", verbose_name="Sobrescrever Config. Global do Badge 'Novo'?"),
        ),
    ]
