# Generated by Django 5.2 on 2025-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_mangachapterpage_force_show_new_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapterpage',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número de vezes que este capítulo foi visualizado.', verbose_name='Visualizações'),
        ),
    ]
