# Generated by Django 5.2 on 2025-06-17 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0017_mangachapterpage_views'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Arquivo de Imagem Criptografada', 'verbose_name_plural': 'Arquivos de Imagem Criptografada'},
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='chapterimage',
            name='relative_path',
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='encrypted_file',
            field=models.FileField(help_text='Armazena a fatia da imagem no formato .enc criptografado.', null=True, upload_to='encrypted_manga_slices/', verbose_name='Arquivo de Fatia Criptografada (.enc)'),
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo'),
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='Selecione uma imagem para ser a capa deste capítulo específico. Se deixado em branco, usará a capa da obra. Esta imagem PODE ser selecionada na tela de upload por pastas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail Personalizada (Opcional)'),
        ),
    ]
