# Generated by Django 5.2 on 2025-06-17 19:36

import django.db.models.deletion
import manga.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0018_alter_chapterimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-favorited_at'], 'verbose_name': 'Favorito de Mangá', 'verbose_name_plural': 'Favoritos de Mangá'},
        ),
        migrations.AlterModelOptions(
            name='mangachapterpage',
            options={'ordering': ['-release_date', '-path'], 'verbose_name': 'Página de Capítulo', 'verbose_name_plural': 'Páginas de Capítulo'},
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='encrypted_file',
            field=models.FileField(help_text='Armazena a fatia da imagem no formato .enc criptografado.', null=True, upload_to=manga.models.chapter_image_upload_path, verbose_name='Arquivo de Fatia Criptografada (.enc)'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
