# Generated by Django 5.2 on 2025-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterpage',
            name='cover',
            field=models.ImageField(blank=True, help_text='Thumbnail específica para este capítulo. Salva fora da biblioteca do Wagtail.', null=True, upload_to='chapter_thumbnails/', verbose_name='Thumbnail do Capítulo'),
        ),
    ]
