# Generated by Django 5.2 on 2025-06-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0020_alter_mangachapterpage_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='is_vip',
        ),
    ]
