# Generated by Django 5.2 on 2025-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0021_remove_mangachapterpage_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapterpage',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Marque se este capítulo for exclusivo para assinantes VIP.', verbose_name='Capítulo VIP?'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='default_chapters_are_vip',
            field=models.BooleanField(default=False, help_text='Se marcado, novos capítulos criados para este mangá serão marcados como VIP automaticamente.', verbose_name='Capítulos Novos são VIP por Padrão?'),
        ),
    ]
