# Generated by Django 5.2 on 2025-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0022_mangachapterpage_is_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='chapters_are_vip',
            field=models.BooleanField(default=False, help_text='Se marcado, TODOS os capítulos desta obra exigirão uma assinatura VIP para serem acessados.', verbose_name='Obra VIP?'),
        ),
    ]
