# Generated by Django 5.2 on 2025-06-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0023_mangapage_chapters_are_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='chapters_are_vip',
            field=models.BooleanField(default=False, help_text='Se marcado, TODOS os capítulos desta obra exigirão uma assinatura VIP e a obra será escondida de não-assinantes.', verbose_name='Obra VIP?'),
        ),
    ]
