# Generated by Django 5.2 on 2025-06-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0024_alter_mangapage_chapters_are_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Contador de Visualizações'),
        ),
    ]
