# Generated by Django 5.2 on 2025-06-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0025_mangapage_views_count'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='cover',
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail do Capítulo (Opcional)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='is_up_to_date',
            field=models.BooleanField(default=False, help_text='Marque se os capítulos postados estão em dia com os lançamentos originais.', verbose_name='Obra em Dia?'),
        ),
    ]
