# Generated by Django 5.2 on 2025-06-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0026_remove_mangachapterpage_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapterpage',
            name='free_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que este capítulo se tornará gratuito. Deixe em branco se a regra de tempo não se aplica.', null=True, verbose_name='Disponível gratuitamente em'),
        ),
    ]
