# Generated by Django 5.2 on 2025-06-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0027_mangachapterpage_free_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapterpage',
            name='free_at',
        ),
        migrations.AlterField(
            model_name='mangachapterpage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail específica para este capítulo. Salva fora da biblioteca do Wagtail.', null=True, upload_to='chapter_thumbnails/%Y/%m/', verbose_name='Thumbnail do Capítulo'),
        ),
    ]
