# Generated by Django 5.2 on 2025-06-27 20:08

import manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0028_remove_mangachapterpage_free_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapterpage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail específica para este capítulo. Salva fora da biblioteca do Wagtail.', null=True, upload_to=manga.models.chapter_thumb_upload_path, verbose_name='Thumbnail do Capítulo'),
        ),
    ]
