# Generated by Django 5.2 on 2025-06-28 02:36

import manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0029_alter_mangachapterpage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimage',
            name='encrypted_file',
            field=models.FileField(help_text='Armazena a fatia da imagem no formato .enc criptografado.', max_length=255, null=True, upload_to=manga.models.chapter_image_upload_path, verbose_name='Arquivo de Fatia Criptografada (.enc)'),
        ),
    ]
