# Generated by Django 5.2 on 2025-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0030_alter_chapterimage_encrypted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='current_donations',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Quantidade de moedas doadas até agora para o próximo capítulo.', verbose_name='Moedas Atuais na Meta'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='donation_goal',
            field=models.PositiveIntegerField(default=0, help_text='Defina a meta de moedas para o lançamento do próximo capítulo. 0 para desativar.', verbose_name='Meta de Moedas para Próximo Cap.'),
        ),
    ]
