# Generated by Django 5.2 on 2025-07-18 02:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0031_mangapage_current_donations_mangapage_donation_goal'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('relation_type', models.CharField(choices=[('shared_universe', 'Universo Compartilhado'), ('prequel', 'Prequel'), ('sequel', 'Sequel'), ('spin_off', 'Spin-off'), ('main_story', 'História Principal'), ('side_story', 'História Paralela'), ('pre_serialization', 'Pré-serialização'), ('alternative_version', 'Versão Alternativa')], max_length=50, verbose_name='Tipo de Relação')),
                ('source_work', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='manga.mangapage', verbose_name='Obra de Origem')),
                ('target_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='wagtailcore.page', verbose_name='Obra Relacionada')),
            ],
            options={
                'verbose_name': 'Relação de Obra',
                'verbose_name_plural': 'Relações de Obras',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
