# Generated by Django 5.2 on 2025-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0032_workrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='donation_notifications_sent',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Notificações de Meta Enviadas'),
        ),
    ]
