# Generated by Django 5.2 on 2025-07-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0033_mangapage_donation_notifications_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='scanlator',
            field=models.CharField(blank=True, max_length=255, verbose_name='Scanlator'),
        ),
    ]
