# Generated by Django 5.2 on 2025-07-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0034_mangapage_scanlator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='recent_vip_chapters_count',
            field=models.PositiveIntegerField(default=0, help_text='Defina quantos dos capítulos mais recentes serão exclusivos para VIPs (ex: 3). Só funciona se a opção acima estiver marcada.', verbose_name='Quantidade de Capítulos Recentes VIP'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='chapters_are_vip',
            field=models.BooleanField(default=False, help_text='Se marcado, TODOS os capítulos desta obra exigirão uma assinatura VIP e a obra será escondida de não-assinantes.', verbose_name='Obra Inteira é VIP?'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='default_chapters_are_vip',
            field=models.BooleanField(default=False, help_text='Se marcado, os capítulos mais recentes (definido abaixo) serão VIP.', verbose_name='Ativar VIP para Caps. Recentes?'),
        ),
    ]
