# Generated by Django 5.2 on 2025-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0035_mangapage_recent_vip_chapters_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='donation_system_active',
            field=models.BooleanField(default=False, help_text='Marque para habilitar a funcionalidade de meta de doação para esta obra.', verbose_name='Ativar Sistema de Doação?'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='reset_donation_goal_on_save',
            field=models.BooleanField(default=False, help_text="Marque esta caixa e salve para zerar o contador de 'Moedas Atuais na Meta'.", verbose_name='Zerar Moedas Atuais ao Salvar?'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='current_donations',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de moedas doadas até agora para o próximo capítulo.', verbose_name='Moedas Atuais na Meta'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='is_up_to_date',
            field=models.BooleanField(default=False, help_text='Marque se os capítulos postados estão em dia com os lançamentos originais. Isso desativará a caixa de doação.', verbose_name='Obra em Dia?'),
        ),
    ]
