# Generated by Django 5.2 on 2025-07-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0036_mangapage_donation_system_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='vip_base_release_days',
            field=models.PositiveIntegerField(default=7, help_text='Tempo de espera, em dias, para os capítulos do degrau mais recente.', verbose_name='Tempo Máx. de Espera (dias)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='vip_days_decrease_per_tier',
            field=models.PositiveIntegerField(default=2, help_text='Quantos dias de espera são removidos a cada degrau mais antigo. Ex: 2.', verbose_name='Redução de Tempo por Degrau (dias)'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='vip_tier_size',
            field=models.PositiveIntegerField(default=3, help_text="Quantos capítulos formam um 'degrau' de tempo de espera. Ex: 3.", verbose_name='Tamanho do Degrau VIP (caps)'),
        ),
    ]
