# Generated by Django 5.2 on 2025-07-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0037_mangapage_vip_base_release_days_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapterpage',
            name='background_music',
            field=models.ForeignKey(blank=True, help_text='Opcional. Escolha um arquivo de áudio (MP3, OGG) para tocar durante a leitura deste capítulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Trilha Sonora de Fundo (BGM)'),
        ),
    ]
