# Generated by Django 5.2 on 2025-07-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0038_mangachapterpage_background_music'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Lido em')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='manga.mangachapterpage', verbose_name='Capítulo Lido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Histórico',
                'verbose_name_plural': 'Registros de Histórico',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
