# Generated by Django 5.2 on 2025-08-09 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0039_readinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='target_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='manga.mangapage', verbose_name='Obra Relacionada'),
        ),
    ]
