# Generated by Django 5.1.8 on 2025-05-04 17:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_scan_name', models.CharField(blank=True, help_text='Exibido no rodapé. Se vazio, pode usar o Nome do Site padrão.', max_length=100, verbose_name='Nome no Rodapé')),
                ('footer_credits', models.CharField(blank=True, default='Desenvolvido por Stalker', max_length=200, verbose_name='Créditos (Rodapé)')),
                ('discord_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do Discord')),
                ('donation_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link de Doação')),
                ('donation_message', wagtail.fields.RichTextField(blank=True, help_text='Mensagem opcional exibida perto do link de doação na página inicial.', null=True, verbose_name='Mensagem de Doação (Home)')),
                ('dmca_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Texto DMCA')),
                ('privacy_policy_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Texto Política de Privacidade')),
                ('terms_of_use_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Texto Termos de Uso')),
                ('activate_slider', models.BooleanField(default=False, help_text='Marque para exibir o slider de imagens na página inicial.', verbose_name='Ativar Slider na Home?')),
                ('color_navbar', models.CharField(blank=True, default='#171717', help_text='Padrão: #171717', max_length=7, verbose_name='Cor Fundo Navbar')),
                ('color_background', models.CharField(blank=True, default='#000000', help_text='Padrão: #000000', max_length=7, verbose_name='Cor Fundo Principal')),
                ('color_text', models.CharField(blank=True, default='#e0e0e0', help_text='Padrão: #e0e0e0', max_length=7, verbose_name='Cor Texto Principal')),
                ('color_accent', models.CharField(blank=True, default='#00B982', help_text='Padrão: #00B982', max_length=7, verbose_name='Cor de Destaque (Links, Badges)')),
                ('adsense_code', models.TextField(blank=True, help_text='Cole aqui o script de anúncio principal. Pode ser inserido no <head> ou <body> via template.', null=True, verbose_name='Código Google AdSense (ou outro)')),
                ('favicon', models.ForeignKey(blank=True, help_text='Ícone exibido na aba do navegador (idealmente .ico ou .png 32x32 ou maior).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('logo', models.ForeignKey(blank=True, help_text='Logo principal exibido no cabeçalho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo do Site')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações Globais do Site',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.URLField(blank=True, help_text='Use apenas se não houver Link Interno.', verbose_name='Link Externo (URL)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda (Opcional)')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Slide')),
                ('link_page', models.ForeignKey(blank=True, help_text='Se preenchido, ignora o Link Externo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Link Interno (Página)')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='core.globalsettings')),
            ],
            options={
                'verbose_name': 'Item do Slider',
                'verbose_name_plural': 'Itens do Slider',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
