# Generated by Django 5.1.8 on 2025-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_client_id', models.CharField(blank=True, help_text='Obtido do Google Cloud Console.', max_length=255, verbose_name='Google Client ID')),
                ('google_client_secret', models.CharField(blank=True, help_text='Obtido do Google Cloud Console. Mantenha em segredo.', max_length=255, verbose_name='Google Client Secret')),
                ('discord_client_id', models.CharField(blank=True, help_text='Obtido do Discord Developer Portal.', max_length=255, verbose_name='Discord Client ID')),
                ('discord_client_secret', models.CharField(blank=True, help_text='Obtido do Discord Developer Portal. Mantenha em segredo.', max_length=255, verbose_name='Discord Client Secret')),
            ],
            options={
                'verbose_name': 'Credenciais de Login Social (OAuth)',
            },
        ),
    ]
