# Generated by Django 5.1.8 on 2025-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialprovidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='color_border',
            field=models.CharField(blank=True, default='#27272a', help_text='Padrão: #27272a', max_length=7, verbose_name='Cor Borda'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_button_primary_text',
            field=models.CharField(blank=True, default='#ffffff', help_text='Padrão: #ffffff', max_length=7, verbose_name='Cor Texto Botão Primário'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_button_secondary_bg',
            field=models.CharField(blank=True, default='#333333', help_text='Padrão: #333333', max_length=7, verbose_name='Cor Fundo Botão Secundário'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_button_secondary_border',
            field=models.CharField(blank=True, default='#555555', help_text='Padrão: #555555', max_length=7, verbose_name='Cor Borda Botão Secundário'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_button_secondary_text',
            field=models.CharField(blank=True, default='#dddddd', help_text='Padrão: #dddddd', max_length=7, verbose_name='Cor Texto Botão Secundário'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_card_background',
            field=models.CharField(blank=True, default='#18181b', help_text='Padrão: #18181b', max_length=7, verbose_name='Cor Fundo Card'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_danger',
            field=models.CharField(blank=True, default='#ef4444', help_text='Padrão: #ef4444', max_length=7, verbose_name='Cor Perigo'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_input_background',
            field=models.CharField(blank=True, default='#27272a', help_text='Padrão: #27272a', max_length=7, verbose_name='Cor Fundo Input'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_input_border',
            field=models.CharField(blank=True, default='#3f3f46', help_text='Padrão: #3f3f46', max_length=7, verbose_name='Cor Borda Input'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_section_background',
            field=models.CharField(blank=True, default='#101013', help_text='Padrão: #101013', max_length=7, verbose_name='Cor Fundo Seção'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='color_text_light',
            field=models.CharField(blank=True, default='#a0a0a0', help_text='Padrão: #a0a0a0', max_length=7, verbose_name='Cor Texto Claro'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='comment_provider',
            field=models.CharField(choices=[('none', 'Nenhum Sistema de Comentários'), ('disqus', 'Disqus'), ('custom', 'Sistema Próprio (Custom)')], default='disqus', help_text='Escolha o sistema de comentários a ser usado no site.', max_length=50, verbose_name='Provedor de Comentários'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='disqus_shortname',
            field=models.CharField(blank=True, help_text="Seu 'shortname' único do site Disqus (ex: meusite). Necessário se 'Disqus' for selecionado.", max_length=100, verbose_name='Disqus Shortname'),
        ),
    ]
