# Generated by Django 5.1.8 on 2025-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalsettings_color_border_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='new_chapter_days_threshold',
            field=models.PositiveIntegerField(default=2, help_text="Capítulos publicados dentro deste número de dias serão marcados como 'NOVO'. Ex: 2 para 48 horas.", verbose_name="Limite de Dias para Capítulo 'Novo'"),
        ),
    ]
