# Generated by Django 5.1.8 on 2025-05-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globalsettings_new_chapter_days_threshold'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='new_chapter_badge_image',
            field=models.ForeignKey(blank=True, help_text='Se selecionado, esta imagem/GIF substituirá o texto padrão do badge. Mantenha pequeno (ex: 30x15px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Imagem/GIF Padrão do Badge 'Novo Capítulo' (Opcional)"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='new_chapter_badge_text',
            field=models.CharField(blank=True, default='NOVO!', help_text='Texto exibido no badge (ex: NOVO!, RECENTE). Deixe em branco se preferir usar apenas a imagem/GIF, ou para não mostrar texto.', max_length=20, verbose_name="Texto Padrão do Badge 'Novo Capítulo'"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_accent',
            field=models.CharField(blank=True, default='#00B982', help_text='Padrão: #00B982', max_length=7, verbose_name='Cor de Destaque'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='new_chapter_days_threshold',
            field=models.PositiveIntegerField(default=2, help_text='Capítulos publicados dentro deste número de dias exibirão o badge automaticamente (se o texto ou imagem global do badge estiverem definidos).', verbose_name='Limite de Dias para Badge Automático'),
        ),
    ]
