# Generated by Django 5.2 on 2025-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_globalsettings_new_chapter_badge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='livepix_widget_url',
            field=models.URLField(blank=True, help_text="Cole aqui o URL 'embed' completo do widget do LivePix. Deixe em branco para não exibir.", null=True, verbose_name='URL do Widget LivePix (Home)'),
        ),
    ]
