# Generated by Django 5.2 on 2025-06-19 05:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalsettings_livepix_widget_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='livepix_client_id',
            field=models.CharField(blank=True, help_text='Client ID obtido do painel de desenvolvedor do LivePix.', max_length=255, verbose_name='LivePix Client ID'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='livepix_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret obtido do painel de desenvolvedor. Mantenha em segredo.', max_length=255, verbose_name='LivePix Client Secret'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='activate_slider',
            field=models.BooleanField(default=False, verbose_name='Ativar Slider na Home?'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='adsense_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código Google AdSense (ou outro)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_accent',
            field=models.CharField(blank=True, default='#00B982', max_length=7, verbose_name='Cor de Destaque'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_background',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Cor Fundo Principal'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_border',
            field=models.CharField(blank=True, default='#27272a', max_length=7, verbose_name='Cor Borda'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_button_primary_text',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Cor Texto Botão Primário'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_button_secondary_bg',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='Cor Fundo Botão Secundário'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_button_secondary_border',
            field=models.CharField(blank=True, default='#555555', max_length=7, verbose_name='Cor Borda Botão Secundário'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_button_secondary_text',
            field=models.CharField(blank=True, default='#dddddd', max_length=7, verbose_name='Cor Texto Botão Secundário'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_card_background',
            field=models.CharField(blank=True, default='#18181b', max_length=7, verbose_name='Cor Fundo Card'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_danger',
            field=models.CharField(blank=True, default='#ef4444', max_length=7, verbose_name='Cor Perigo'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_input_background',
            field=models.CharField(blank=True, default='#27272a', max_length=7, verbose_name='Cor Fundo Input'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_input_border',
            field=models.CharField(blank=True, default='#3f3f46', max_length=7, verbose_name='Cor Borda Input'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_navbar',
            field=models.CharField(blank=True, default='#171717', max_length=7, verbose_name='Cor Fundo Navbar'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_section_background',
            field=models.CharField(blank=True, default='#101013', max_length=7, verbose_name='Cor Fundo Seção'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_text',
            field=models.CharField(blank=True, default='#e0e0e0', max_length=7, verbose_name='Cor Texto Principal'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='color_text_light',
            field=models.CharField(blank=True, default='#a0a0a0', max_length=7, verbose_name='Cor Texto Claro'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='comment_provider',
            field=models.CharField(choices=[('none', 'Nenhum Sistema de Comentários'), ('disqus', 'Disqus'), ('custom', 'Sistema Próprio (Custom)')], default='disqus', max_length=50, verbose_name='Provedor de Comentários'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='disqus_shortname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Disqus Shortname'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='donation_message',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Mensagem de Doação (Home)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='footer_scan_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome no Rodapé'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='livepix_widget_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Widget LivePix (Home)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo do Site'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='new_chapter_badge_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Imagem/GIF Padrão do Badge 'Novo Capítulo' (Opcional)"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='new_chapter_badge_text',
            field=models.CharField(blank=True, default='NOVO!', max_length=20, verbose_name="Texto Padrão do Badge 'Novo Capítulo'"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='new_chapter_days_threshold',
            field=models.PositiveIntegerField(default=2, verbose_name='Limite de Dias para Badge Automático'),
        ),
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='discord_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discord Client ID'),
        ),
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='discord_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Discord Client Secret'),
        ),
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='google_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Client ID'),
        ),
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='google_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Client Secret'),
        ),
    ]
