# Generated by Django 5.2 on 2025-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_globalsettings_livepix_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='recent_vip_chapter_limit',
            field=models.PositiveIntegerField(default=5, help_text='Para obras não-VIP, define quantos dos últimos capítulos lançados serão exclusivos para assinantes.', verbose_name='Limite de Capítulos Recentes VIP'),
        ),
    ]
