# Generated by Django 5.2 on 2025-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_globalsettings_recent_vip_chapter_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='discord_bot_token',
            field=models.CharField(blank=True, help_text='O token do seu bot para gerenciar cargos e enviar anúncios. Mantenha em segredo.', max_length=255, null=True, verbose_name='Token do Bot do Discord'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='discord_guild_id',
            field=models.CharField(blank=True, help_text='O ID do seu servidor do Discord.', max_length=255, null=True, verbose_name='ID do Servidor (Guild)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='discord_vip_role_id',
            field=models.CharField(blank=True, help_text='O ID do cargo que será dado aos assinantes VIP.', max_length=255, null=True, verbose_name='ID do Cargo VIP'),
        ),
    ]
