# Generated by Django 5.2 on 2025-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_globalsettings_discord_bot_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='adsense_code',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_al5sm',
            field=models.TextField(blank=True, help_text='Cole o script do Al5sm (z=9469898) aqui.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_groleegni',
            field=models.TextField(blank=True, help_text='Cole o script do Groleegni (z=9469963) aqui.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_loajawun',
            field=models.TextField(blank=True, help_text='Cole o script do Loajawun (z=9469961) aqui.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_monetag',
            field=models.TextField(blank=True, help_text='Cole o script da meta tag do Monetag aqui.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_pertawee',
            field=models.TextField(blank=True, help_text='Cole o script do Pertawee (z=9469896) aqui.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_stoampaliy',
            field=models.TextField(blank=True, help_text='Cole o script do Stoampaliy (z=9469964) aqui.', null=True),
        ),
    ]
