# Generated by Django 5.2 on 2025-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_globalsettings_adsense_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_push_antiblock',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469897', null=True, verbose_name='Push Notifications (Anti-AdBlock)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_al5sm',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469898', null=True, verbose_name='OnClick (Popunder)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_groleegni',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469963', null=True, verbose_name='Native Banner (Interstitial)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_loajawun',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469961', null=True, verbose_name='In-Page Push'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_monetag',
            field=models.TextField(blank=True, help_text="Cole a meta tag <meta name='monetag'...> aqui.", null=True, verbose_name='Monetag (Meta Tag de Verificação)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_pertawee',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469896', null=True, verbose_name='Push Notifications'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ad_script_stoampaliy',
            field=models.TextField(blank=True, help_text='ID da Zona: 9469964', null=True, verbose_name='Vignette Banner'),
        ),
    ]
