# Generated by Django 5.2 on 2025-06-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_globalsettings_ad_script_push_antiblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ad_script_multizone',
            field=models.TextField(blank=True, help_text='Cole o script do anúncio Multizone aqui.', null=True, verbose_name='Monetag (Multizone)'),
        ),
    ]
