# Generated by Django 5.2 on 2025-06-22 18:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_globalsettings_ad_script_multizone'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='activate_premium_banner',
            field=models.BooleanField(default=False, verbose_name='Ativar Banner Premium na Home?'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_badge',
            field=models.CharField(blank=True, default='Premium', help_text='Texto pequeno acima do título principal.', max_length=100, verbose_name='Badge do Banner'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_benefits_title',
            field=models.CharField(blank=True, default='Vantagens Premium', max_length=100, verbose_name='Título da Lista de Benefícios'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_button_link',
            field=models.ForeignKey(blank=True, help_text='Selecione a página de planos de assinatura para onde o botão levará.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Destino do Botão'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_button_text',
            field=models.CharField(blank=True, default='Assinar Agora', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_price',
            field=models.CharField(blank=True, default='4,99€/mês', max_length=50, verbose_name='Texto de Preço'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_title',
            field=models.CharField(blank=True, default='Desbloqueie funcionalidades exclusivas', max_length=200, verbose_name='Título do Banner'),
        ),
        migrations.CreateModel(
            name='PremiumBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255, verbose_name='Texto do Benefício')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_benefits', to='core.globalsettings')),
            ],
            options={
                'verbose_name': 'Benefício Premium',
                'verbose_name_plural': 'Benefícios Premium',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
