# Generated by Django 5.2 on 2025-06-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_globalsettings_activate_premium_banner_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='premium_banner_button_link',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='premium_banner_gif',
            field=models.ForeignKey(blank=True, help_text='Opcional. Um GIF para ser exibido ao lado do banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='GIF Animado do Banner'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='premium_banner_badge',
            field=models.CharField(blank=True, default='Premium', max_length=100, verbose_name='Badge do Banner'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='premium_banner_price',
            field=models.CharField(blank=True, default='R$ 5,00/mês', max_length=50, verbose_name='Texto de Preço'),
        ),
    ]
