# Generated by Django 5.2 on 2025-06-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_globalsettings_premium_banner_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='use_canvas_reader',
            field=models.BooleanField(default=True, help_text='Se marcado, as páginas dos capítulos serão exibidas em <canvas> para dificultar o download. Se desmarcado, usará a tag <img> padrão.', verbose_name='Usar Canvas para Leitor de Capítulos'),
        ),
    ]
