# Generated by Django 5.2 on 2025-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_globalsettings_use_canvas_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='cloudflare_api_token',
            field=models.CharField(blank=True, help_text="Crie um token com permissão de 'Purge Cache'. Ele será usado para limpar o cache automaticamente.", max_length=255, verbose_name='Cloudflare API Token'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, help_text='O ID da Zona encontrado no painel do Cloudflare. Necessário para limpar o cache.', max_length=255, verbose_name='Cloudflare Zone ID'),
        ),
    ]
