# Generated by Django 5.2 on 2025-07-09 19:29

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_globalsettings_cloudflare_api_token_and_more'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Ex: Gostei, Amei', max_length=50, verbose_name='Nome')),
                ('type_id', models.SlugField(help_text="Identificador único, ex: 'like', 'love'", unique=True, verbose_name='ID do Tipo')),
                ('icon', models.FileField(help_text='Ícone da reação (.svg, .png)', upload_to='reactions/', verbose_name='Ícone')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_types', to='core.globalsettings')),
            ],
            options={
                'verbose_name': 'Tipo de Reação',
                'verbose_name_plural': 'Tipos de Reação',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='wagtailcore.page')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='core.reactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reação de Usuário',
                'verbose_name_plural': 'Reações de Usuários',
                'unique_together': {('user', 'page')},
            },
        ),
    ]
