# Generated by Django 5.2 on 2025-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reactiontype_userreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='Client ID da sua aplicação PayPal para pagamentos reais.', max_length=255, verbose_name='PayPal Client ID (Live)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret para pagamentos reais. Mantenha em segredo.', max_length=255, verbose_name='PayPal Client Secret (Live)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_receiver_email',
            field=models.EmailField(blank=True, help_text='O email da sua conta de vendedor do PayPal.', max_length=254, verbose_name='PayPal Receiver Email'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_sandbox_client_id',
            field=models.CharField(blank=True, help_text='Client ID para o ambiente de testes (Sandbox).', max_length=255, verbose_name='PayPal Client ID (Sandbox)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='paypal_sandbox_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret para o ambiente de testes. Mantenha em segredo.', max_length=255, verbose_name='PayPal Client Secret (Sandbox)'),
        ),
    ]
