# Generated by Django 5.2 on 2025-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_globalsettings_paypal_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_currency',
            field=models.CharField(choices=[('BRL', 'Real Brasileiro (R$) - Ativa LivePix'), ('USD', 'Dólar Americano (US$) - Ativa PayPal')], default='BRL', help_text='Selecione a moeda principal para os preços e o método de pagamento a ser exibido.', max_length=3, verbose_name='Moeda Padrão do Site'),
        ),
    ]
