BBBB BBBBBB BBBBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFBBBBBX XXXXX XX XXXXXXXX XXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXFFFFFFFFXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXBBB BBBBBBXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX XX XXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXX XX XXXXXXX

                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX