BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BB BBBBBBBB
                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFF XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBB
                    XXXXX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXXXXXXX
                BBBBB
            XXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Início') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX gettext(u'Comics') XXXX
                
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Vip') XX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Vip') XXXXXXX
                XXXX

                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Loja') XXXXXXX
                XXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Discord') X XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Discord') XXXXXXX
                    XXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Apoiar') XX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Apoiar') XXXXXXX
                    XXXX
                BBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Pesquisar comics...') X XXXXXXXXXXXX gettext(u'Pesquisar') X XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Buscar') XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBB BBB BB BBBBBBBBBBBBBB
                                XXXX XXXXXX XXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXX
                            BBBB
                                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        BBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Meu Perfil') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Meus Favoritos') XXXXXXXXX
                        
                        XXXX XXXX XX XXXXXXXXX XXXXXXXXX XXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Histórico') XXXXXXXXX
                        
                        BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Admin Wagtail') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Admin Django') XXXXXXXXX
                        BBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Sair') 
                                XXXXXXXXX
                            XXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
            BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXX gettext(u'Login') X XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Login') XXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXX gettext(u'Registrar') X XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Registrar') XXXXXXX
                XXXX
            BBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Pesquisar comics...') X XXXXXXXXXXXX gettext(u'Pesquisar') X XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Buscar') XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXX
            XXXXXX XXXXXXXXX gettext(u'Início') XXXXXXXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Comics') XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Vip') XXXXXXXXX
            
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Loja') XXXXXXXXX
    
            BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Meu Perfil') XXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Meus Favoritos') XXXXXXXXX

                XXXX XXXX XX XXXXXXXXX XXXXXXXX XXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Histórico') XXXXXXXXX

                BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Admin Wagtail') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Admin Django') XXXXXXXXX
                BBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
                        BBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Sair') 
                        XXXXXXXXX
                    XXXXXXX
                XXXXX
            BBBB
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Login') XXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Registrar') XXXXXXXXX
            BBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Discord') XXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Apoiar') XXXXXXXXX
            BBBBB
        XXXXX
    XXXXXX
XXXXXX