BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Loja de Badges') BBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXX XXXXX
X
XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXX
X
XXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
X
XXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXX
X

XX XXXX XXXXXX XX XXXXXXXX XXXXXXXXX XXXX XX
XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX X XXXXXX XXXXXXXX XXXX XX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX
X
XX XXXX XXX XX XXXXXXXX XXXXXXXXX XXXX XX

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX X XXXX XXXX XXXX XXXXXXX XX XX XXXXX X XXX XXX XXXX XXXXXXX XX XX XXXXX
X
XXXXXXXXXXXXXX X
    XXXXXXX X XXXX XXXX XXXXX
    XXXXXXXX XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXX
X
XXXXXXXXXXX XX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXX
X
XXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
X
XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX
X
XXXXXXXXXXXX XXXXXXXXXX X
    XXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
X
XXXXXXXXXXX XXXX X
    XXXXXX XXXXX
X
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXX XXXXXXX
X
XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Loja de Badges') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXX XXXXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
             gettext(u'Seu saldo:')  XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXFFFFFFFFFXXXXXXXXX
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                
                 #

                XXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXX
                        BB BBBBBBBBBBBBBBBBXX XXXXXXX XXXXXXXXXXBBBBB
                    XXXXXX
                    XXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                 #

                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX 
                    XXXXXX
                    
                    BB BBBBBBBB BB BBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX gettext(u'Adquirido') XXXXXXXXX
                    BBBB
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Comprar') XXXXXXXXX
                    BBBBB
                XXXXXX

            XXXXXX
        BBBBB
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Nenhum badge disponível na loja no momento.') XXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXX X XXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Processando...') XX
            XXXXXXXXXXXXXXXXXXXXXX X XXX
            
            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXX
                XX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XX
            XX
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX
            XXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX

                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXX
                    
                    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX

                    XXXXXXXXXXXXXXXX X X gettext(u'Adquirido') XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXX X XXXXXX
                    XXXXXXXXXXXXXX X X gettext(u'Comprar') XX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Ocorreu um erro de conexão. Tente novamente.') XX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXX X XXXXXX
                XXXXXXXXXXXXXX X X gettext(u'Comprar') XX
            XXX
        XXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB