BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Editar Perfil') BBBBBBBB

BBBBB BBBBBBBBB

XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XX
        XXXXX XXXXXX X X XXX
        XXXXXXX XXXX
        XXXXXXX XXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXX XX
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXX
        XXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXX XX
    X

    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX XX
        XXXXXXX XX
    X

    XXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXX XXXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXX XXXXXXX
        XXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXX XXXXX XXX XXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXX XXXX X XXXX XXX XXXXX XXXX XXXX XXX XXX XXX XXXXX
    X

    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Editar Perfil') XXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Foto de Perfil') XXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                             XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                             XXXXX gettext(u'User avatar') X
                             XXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Formatos suportados: JPG, PNG (Max. 5MB)') XXXX
                        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Alterar Foto') 
                            XXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX gettext(u'Salvar Avatar') XXXXXXXXX
                        XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
                                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBB
                            XXXXXX
                        BBBBB
                        BBB BBBBBBB BB BBBBBBBB
                            BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                            BBBB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                            BBBBB
                        BBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Informações Pessoais') XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Nome de Usuário') XXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFXXXXBBBBB
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Nome de Exibição') XXXXXXXX
                        
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFXXXXBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Biografia') XXXXX
                XXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFXXXXBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Conte um pouco sobre você (max. 200 caracteres)') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Badges Ativos') XXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    
                BBBB
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Você ainda não possui nenhum badge. Visite a loja para adquirir!') XXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
                        FFFFFFFFF
                    XXXXXX
                BBBBB
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Escolha até 2 badges para exibir no seu perfil.') XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'E-mail') XXXXX
                XXXXX
                    
                    BB BBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFXXXXBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Este é o e-mail associado à sua conta') XXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX gettext(u'Salvar Alterações') XXXXXXXXX
            XXXXXX
        XXXXXXX

    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXX gettext(u'Formato de arquivo inválido. Apenas JPG e PNG são permitidos.') XXX
                    XXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXXXX
                X
                XX XXXXXXXXXX X X X XXXX X XXXXX X XX XXX
                    XXXXXXX gettext(u'Arquivo muito grande. O tamanho máximo é 5MB.') XXX
                    XXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXXXX
                X

                XXXXX XXXXXX X XXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X
XXX
XXXXXXXXX
BBBBBBBB BBBBBBBB