BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBB

BBBBB BBBBBXXX XXXXXX X BBBBBBBB BBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXX XXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXX X X
            XXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBB
            XXXX XXXXXX
                 XXXXXXXXXXX XX X
                 XXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXX XXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXX
        BBBBB

        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
                
            BBBB
                FFFFFFFFFFFFFFFFFFFFF
            BBBBB
        XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXFFFFFFFFFFFFXXXX
        XXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Editar Perfil') 
            XXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Sair') 
                XXXXXXXXX
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Vincular Contas') XXXXX
            BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Conectar com Discord') 
                    XXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX gettext(u'Discord Conectado') XXXXXXX
                    XXXXXX
                BBBBB

                BB BBB BBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX gettext(u'Em breve') XX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Conectar com Google (Em breve)') 
                    XXXXXXXXX
                BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX gettext(u'Google Conectado') XXXXXXX
                    XXXXXX
                BBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX 
                            XXX XXXXX XXXXXXX XXX FFFFFFFFFFFFX
                        XXXXXXX
                    BBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXX XXXXXX XXX XXXXXXXXXX XXXXXX
                        XXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    BBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX 
                        FFFFFFFFF XXXXXX
                    XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXX
                                BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXBBBBB
                                
                            XXXXXXX
                        BBBBB
                            XXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX X XXXXXXXX
                XXXXXX
            XXXXXX
            
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
                 gettext(u'Para alterar sua senha, por favor, entre em contato pelo discord com')  XX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB