BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Meus Favoritos') BBBBBBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB

XXXXXXX
    XX XXX XXXX XXXXX X XXXX XXXXXXXXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XX X XXXXX XXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXX XXX XX XXXXXXX XXXXXX XX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX XX XXXXXXXXXXX XXXXX XX XXXXX XX
    X

    XX XXXXXXX XXXX XXXX XXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XX XXX XX XXXXX XX XXXXX XXXX XXXXX XX
        XXXXXXXXXXXXXX XXXX XX XXXXXX XXXXXXXXXXXX XX
        XXXXXXXXX XXXXXXX XX XXXXXXX XXX X XXXXXX XXX XXXX XX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX X XXXXXXXX XXXXXXX XX XXXXX XXXXX XXXXXXXX XX
        XXXXXXX XXX XXXXX XXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX XX XXX XX XXXXX XX XXXXXX X XXXXX XX
    X

    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXX XXXXXX
        XXXXXXXXXXXXX X X XX XX XXXXXXXXX XX XXXX XX
    X

    XXXXXXXXXXXXXXXXXXX XXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX XX XXXXXXX XXX X XXXXXX XXXXX X XXXXXX XXX XXXXXXXXX XX
    X

    XXXXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XX XX XXX XXXX XXXX XXXXXXX XXXX XXXXXXXXX X XXXXXX XX
    X

    XXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXX XXXXX XX X XXXXXX XXX XXXXX XXXXX XX
        XXXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
        XXXXXXXXXXX XXXXX XX XXXXXXX XXXX X XXXXX XX XXXX XX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX XX XXXXX XXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX XX XXXXXXXX XX
    X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Minhas Obras Favoritas') XXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBB
                XXXX XXXX X X XXXXXXXXX XXX X XXXXX XXXX XXX XXX XXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBBBBB
                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XX XXXXXXBBBBBBB BBBBX XXXXXXXXXXXXXXXXXXX
                                    BB BBBBBBBBBB
                                        BBBBB BBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBB
                                        XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    BBBB
                                         XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBBB
                                XXXX

                                XXXX XXXXXXXXXXXXXXXX
                                    XXXX
                                        XX XXXXXXBBBBBBB BBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                                            
                                        XXXX
                                    XXXXX
                                    XXXX XXXXXXXXXXXXXXX
                                        XXX gettext(u'Em: %(date)s') SSS SSSSSSSSXXXX
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXXXXXXXXXX
                                                XXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                                                XXXXXXXXXXXXXXXXXX
                                                XXXXXXX gettext(u'Remover dos Favoritos') XX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        BBBBBBB
                    BBBBBB
                XXXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
                    XXXXXX
                BBBBB

            BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Nenhum favorito ainda') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Quando você marcar obras como favoritas, elas aparecerão aqui.') XXXX
                    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX gettext(u'Explorar Obras') XXXX
                XXXXXX
            BBBBB
        XXXXXX

    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB


BBBBB BBBBBBBB

    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXX

            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXX XX XXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX XX XX XXXX XX XXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX

            XXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXX
                XX
                XXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXX
                XX
            XX
            XXXXXXXXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX X
                XX XXXXXXXXXXXX XXX XXXXXXXXXX X
                    XX XXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXX XXXXXXXXX XXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                        XXXXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX
                    X
                X XXXX X
                    XXXXX XXX XXXXXXXXXXXXXXXXXX XX XX XXX XXX XXXXXXXX X XXXX XXXXXXXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXX XX XXXX XX XXXXXXX X XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXX
        XXX
    XXX
    XXXXXXXXX
BBBBBBBB BBBBBBBB