# Generated by Django 5.2 on 2025-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/%Y/%m/', verbose_name='Imagem Anexada'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_image_spoiler',
            field=models.BooleanField(default=False, verbose_name='Imagem é Spoiler?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
    ]
