# Generated by Django 5.2 on 2025-07-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_image_comment_is_image_spoiler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_image_spoiler',
            new_name='image_is_spoiler',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Texto é Spoiler?'),
        ),
    ]
