BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBBXXXX XX XXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXX XXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXX X
    XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXX X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XX XXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXX XXXXX XXXXXXXXXX X XXXXXXX XXXX XXXX XX XXXXXXXXXXXXXXX
    XXXXXX

    BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFF
                XXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXX XXX XXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    BBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXX XX XXXXXX XXXXXXXXXX XX XXXXXXXX XXXXX XXXX XXXXXX
        XXXXXX
    BBBBB
XXXXXX
BBBBBBBB


BBBBB BBBBBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXX XXXXXXXXX XX XXXX X XXXXX XXXX XXXXXXXXX XXXX XXXX XXX
    XX XXXX XXXXX X X XXXXX XXXX XXXXXXXXXX XX XXX XX XXXXX XXXXXXX
    XXXXX XXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXXX X XXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Redirecionando...') XX
            XXXXXXXXXXXXX X XXXXX

            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXX XXXXXXXXX XX XXXXXX X XXXXX XXXX XX XXXXXXXXX XX XXXXXXXXXXX XXX
                    XX XXXX XXXXXXXXX X XXXXXXXXXXX XX XXXXX XXXX X XXXXXXX X XXXX XXXX
                    XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XX
            XX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXX X
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXX XXX XXXXXXXXXXXXXXXXXXXXX XX X gettext(u'Erro do Servidor:')  XXXXXXXXXXXXXXXXXXXXX
                    XXX
                X
                XXXXXX XXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXX XX X
                XX XXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXX XXX XXXXXXXXXXXXXXXX XX X gettext(u'URL de redirecionamento não recebida.') XXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX
                XXXXXXX gettext(u'Erro:')  X X XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXX
            XXX
        XXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB