BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Planos VIP')  X BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
    
    XXXX XXXX XXXXX XXXX XXX X XXXX XXXXX XXXX XXXXXXX XXX XXXX XXX XXXXXXX XXXX XXXXXX XXXXXXXXXXX XXX
    BBBBBBBBBB

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Nossos Planos VIP') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Apoie nosso trabalho e ganhe acesso a capítulos adiantados e outros benefícios!') 
        XXXX
    XXXXXXXXX

    BB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX
                    
                XXXXXX
            BBBBBB
        XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX  XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'Assinar com PIX') 
                XXXXXXXXX
            XXXXXX
        XXXXXX
    BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXX X XXXXX XX XXXXXXXXXXXX XXXX XXX X XXXX XXXXXX XXXX X XXXXXXXXX
    XX XXXX XXXXX X X XXXXX XXXX X XXXXXXXXXXX XXXXXX XXX X XXXX
    XXXXX XXXXXXXXX X XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXXX X XXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Redirecionando...') XX
            XXXXXXXXXXXXX X XXXXX

            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXX X XXXXX XXXX XX XXXXXXXXX XX XXXXXXXXXXXX
                    XX XXXX XXXXXXX X XXXX XXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XX
            XX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXX X
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXX XXX XXXXXXXXXXXXXXXXXXXXX XX X gettext(u'Erro do Servidor:')  XXXXXXXXXXXXXXXXXXXXX
                    XXX
                X
                XXXXXX XXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXX XX X
                XX XXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXX XXX XXXXXXXXXXXXXXXX XX X gettext(u'URL de redirecionamento não recebida.') XXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX
                XXXXXXX gettext(u'Erro:')  X X XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX X XXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXX
            XXX
        XXX
    XXX
XXX
XXXXXXXXX
BBBBBBBB