BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB

BBBBB BBBBBXXXX X FFFFFFFFFFFFFFFFFFFFBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    FFFFFFFF
                BBBB
                    XXXX XXXXX XX XXXX XXXXX XXX XXX XXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
        XXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB