BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB 

BBBBB BBBBBXXXXXXXX XX XXXXXXXXXXX X FFFFFFFFFFFFFFFFFFFFBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    FFFFFFFF
                BBBB
                    XXXX XXXXX XX XXXXXXXX XX XXXXXXXXXXX XXXXX XXX XXX XXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
        XXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB