BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB

BBBBB BBBBBXXXXXX XX XXX X FFFFFFFFFFFFFFFFFFFFBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    FFFFFFFF
                BBBB
                    XXXX XXXXX XXX XXXXXX XX XXX XXXXX XXX XXX XXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
        XXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB BBBBBBB