 #
 #
 #


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX 
            XXXXXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX 
            XXXXXXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXX
            XXXXXXXXXXXXX 
            XXXXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
            
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBB
                    XXXXXXXXXXXXXX
                BBBBB
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        BBBBBB
        
    XXXXXX
    
    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX
    XXXX
    BBBBB
XXXXXX