# Generated by Django 5.1.8 on 2025-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_avatar_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_avatar',
            field=models.ImageField(blank=True, help_text='Faça upload de uma imagem para seu avatar neste site.', null=True, upload_to='users/site_avatars/', verbose_name='Avatar do Site'),
        ),
    ]
