# Generated by Django 5.2 on 2025-06-02 17:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_location_profile_site_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Como você gostaria de ser chamado no site.', max_length=100, null=True, verbose_name='Nome de Exibição'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site_avatar',
            field=models.ImageField(blank=True, help_text='Faça upload de uma imagem para seu avatar neste site.', null=True, upload_to=accounts.models.user_site_avatar_path, verbose_name='Avatar do Site'),
        ),
    ]
