# Generated by Django 5.2 on 2025-07-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_display_name_alter_profile_site_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moedas',
            field=models.IntegerField(default=0, verbose_name='Saldo de Moedas'),
        ),
    ]
