# Generated by Django 5.2 on 2025-07-23 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_moedas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Apoiador Lendário', max_length=50, unique=True, verbose_name='Nome do Badge')),
                ('description', models.CharField(blank=True, help_text='Uma breve descrição que pode aparecer na loja.', max_length=150, verbose_name='Descrição')),
                ('icon_class', models.CharField(blank=True, help_text="Opcional. Ex: 'fas fa-shield-alt'", max_length=50, verbose_name='Classe do Ícone (Font Awesome)')),
                ('color', models.CharField(default='#4F46E5', help_text='Cor do fundo do badge. Ex: #4F46E5', max_length=7, verbose_name='Cor de Fundo (Hex)')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Cor do texto do badge. Ex: #FFFFFF', max_length=7, verbose_name='Cor do Texto (Hex)')),
                ('price', models.PositiveIntegerField(default=1000, help_text="Custo para comprar este badge. 0 para gratuito (mas ainda precisa ser 'comprado').", verbose_name='Preço em Moedas')),
                ('is_staff_only', models.BooleanField(default=False, help_text='Se marcado, este badge não pode ser comprado e é atribuído manualmente no painel de administração.', verbose_name='Apenas para Staff?')),
            ],
            options={
                'verbose_name': 'Badge Cosmético',
                'verbose_name_plural': 'Loja de Badges',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='active_badge',
            field=models.ForeignKey(blank=True, help_text='O badge que o usuário escolheu exibir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_wearing_this', to='accounts.cosmeticbadge', verbose_name='Badge Ativo'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='accounts.cosmeticbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge de Usuário',
                'verbose_name_plural': 'Inventário de Badges',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
