# Generated by Django 5.2 on 2025-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cosmeticbadge_profile_active_badge_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_badge',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_badges',
            field=models.ManyToManyField(blank=True, help_text='Selecione os badges que o usuário irá exibir.', related_name='users_wearing_this', to='accounts.cosmeticbadge', verbose_name='Badges Ativos'),
        ),
    ]
