# Generated by Django 5.2 on 2025-07-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_active_badge_profile_active_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_badges',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_badge',
            field=models.ForeignKey(blank=True, help_text='O badge que o usuário escolheu para exibir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearers', to='accounts.cosmeticbadge', verbose_name='Badge Ativo'),
        ),
    ]
