# Generated by Django 5.2 on 2025-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_active_badges_profile_active_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_badge',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_badges',
            field=models.ManyToManyField(blank=True, help_text='Os badges que o usuário escolheu para exibir.', related_name='wearers', to='accounts.cosmeticbadge', verbose_name='Badges Ativos'),
        ),
    ]
