# Generated by Django 5.2 on 2025-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_active_badge_profile_active_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticbadge',
            name='is_vip_badge',
            field=models.BooleanField(default=False, help_text='Se marcado, este badge é atribuído automaticamente para usuários VIP.', verbose_name='Badge VIP?'),
        ),
        migrations.AlterField(
            model_name='cosmeticbadge',
            name='is_staff_only',
            field=models.BooleanField(default=False, help_text='Se marcado, este badge é atribuído automaticamente para a equipe e não pode ser comprado.', verbose_name='Badge de Staff?'),
        ),
    ]
