BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXX XXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXXX XXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXX XXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXX XXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X
    XX XXXXXXXXXX XXXX XXXXXXXXX X XXXXX XX XXXXXX XX XXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXX XXXXXXXX XX XXX XXXXX XXXXX X XX XXXXXX XX XXXXXXXX XX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX

BBB BBBB BB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBBBBBB BBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBB
                BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BB BBBBBBBB
                XXXX XXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX
                    
                XXXXXXX
            BBBBB
            
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
                        
                    XXXXXXX
                BBBBB
            BBBBBBB
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBBBBBB BBBBXXXXXX
            XXXXX
            
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
                                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXFFFFFFFFFFXX
                                BBBB
                                    XX XXXXXXBBBBBBB BBBBBBBX XXXXXXXFFFFFFFFFFXX
                                BBBBB
                                        XXXXX XXXXXXXXXXXXXXXXXXXXX
                                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                                            BBBBB
                                            XXXX 
                                            
                                            
                                            
                                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                                            BBBBB
                                        XXXXXXX
                                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBXXXX XXXXXX XXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBXXXXXXXBBBBBBBBBBBB
                                    XXXX
                            XXXXX
                        BBBBBB
                    XXXXX
                BBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX
                BBBBB
            BBBBBBB
        XXXXXX
    XXXXXX
BBBBBB