BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXX XXXXXXXXX X BBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX XX XXXX XX XXX XXXX XX
            XXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXXX XXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX XX XXXXXXXXXX XXXX XXXXXXXXXXXX XX
        X
        XXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXX XX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXX
        X
        XXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XX XXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXX XXXXXXXXX X
            XXXXXXXXXX XXXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Capítulo Bloqueado') XXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'\n            O Capítulo %(chapter_title)s de "%(manga_title)s" é um conteúdo exclusivo.\n        ') 
            S SSSSSSSS SSSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSS S SS SSSSSSSS SSSSSSSSSS
        
    XXXX

     #

    BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXFFFFFFFFFXXXXXXXXXX
        XXXXXX
    BBBBB
     #


    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Não quer esperar?') 
    XXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX gettext(u'Torne-se VIP Agora!') XXXXXXX
    XXXX

XXXXXX
BBBBBBBB