BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBB

BBBBB BBBBBXXX XXXXXXXXX XX XXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX
    XX XXXXXX XXXX X XXXX X XXXX XX XXXXXXXXX XX XXXXXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX XX XX XXXXX XXXXXXX XXX XXXXXXX XXX XXXXX XXXXXXX XX
        XXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXX XX XXXXXX X XXXXX X X XXXXX XXXXXXXXXXXX XX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXX XXXXXX XXXXX XX
    X

    XX XXXXXX XXXX X XXX XXXXXX XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXX XX
        XXXXXX XXXXXXXX           XX XXXXX XXXXX XX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX
BBBBBBBB


BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXX
        XXXXXX

        BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBB
                    
                    XX XXXXXXBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBB
                                BBBBB BBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBB
                                XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX
                            BBBB
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                                XXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            
                            
                            XX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                                    XXXXXXXX FFFFFFFFFFFFFFFF
                                BBBB
                                    XXXXXXXXX FFFFFFFFFFFFFFFF X FFFFFFFFFFFFFFFF
                                BBBBB
                            XXXX
                            
                            
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX FFFFFFFFFFF FFFF FFFFXX
                                XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXX FFFFFFFFFFF
                            XXXXXXXX
                        XXXXXX
                    XXXX
                BBBBBB
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXX XXXXXXXXX X XXXX XXXXXXXXXX XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
            XXXXXX
        BBBBB
    XXXXXX
XXXXXXX
BBBBBBBB