BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBBBBB gettext(u'Uso de Disco') BBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX X XXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXX
        XXXXXXXXXXXXXX X X XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX X
        XXXXXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXX X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX XXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXX XXXXXX   
            XXXXXXX XXXX XXXXX XXXXXXXX XXXXX
            XX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX XX XX
            XXXXXXXXXXXXXX XXXX
            XX XXXXXX XXXX XXXXXXXX XXX XX XX
        X
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX X
        XXXXXXXXX XXXXXX XX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX X
        XXXXXXXXX XXXXXX XX X XXXXXXXX XXXX XXXXX X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX gettext(u'Erro ao obter dados do disco:') XXXXXXXXXXXXX
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX gettext(u'Total:') XXXXXXXXX FFFFFFFFFFFFFFFFFFFFF XXXXXX
                    XXXXXXXXXXX gettext(u'Usado:') XXXXXXXXX FFFFFFFFFFFFFFFFFFFFF XX XFFFFFFFFFFFFFFFFFFFFFXXXXXX
                    XXXXXXXXXXX gettext(u'Livre:') XXXXXXXXX FFFFFFFFFFFFFFFFFFFFF XXXXXX
                XXXXXX

                BB BBBBBBBB BB BBB BBBB BBB BBBBBBB BB BBB BBBB BBB BBBBBBB BB BBB BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXX
                BBBB
                     XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gráfico não disponível devido à falta de dados ou dados zerados.') XXXXXXXXXXXXXXXXXXXXXX
                BBBBB

                BB BBBBBBBBBBBB BBB BBBBBBBBBBBB BB BBBBB
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Informações para o caminho: %(path_checked)s') SSSSSSSSSSS SSSS S SSSSSSSS SSSSSSSSSSSSSSSSXXXX
                BBBBB
            BBBBB
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXX XXXXXXX XXX XXXXXXXXXXX XX XXXXXXXX XXXX XX XXXXX XXXXX
            XXXXX XXXXXXXXXXXX X XFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXX X XFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXX XXXXX
            
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XX XX

            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXX
            XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXX XX XXXXX
            XXXXXXXXXXXXXXXXXX XXXX X XXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XX XXXXX


            XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX XXXXX XXXXX XX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
            X


            XX XXXXXXXXXXXX XX XXXXXXXXXX X X XX XXXXXXXXX X XXX X
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX X
                    XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXX X XXXXXXXX XX XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX
                X
                
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXX XXXX XXXXX
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXX XX XXXX XX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXX


                XXX XXXXXXXXXX X
                    XXXXX XXXXXXXXXXX
                    XXXXX X
                        XXXXXXX XX gettext(u'Espaço Usado (GB)') XX X gettext(u'Espaço Livre (GB)') XXX
                        XXXXXXXXX XX
                            XXXXXX X gettext(u'Uso do Disco') XX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XX
                            XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
                            XXXXXXXXXXXX X
                        XX
                    XX
                    XXXXXXXX X
                        XXXXXXXXXXX XXXXX
                        XXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXX X
                            XXXXXXX X
                                XXXXXXXXX XXXXXXXXX
                                XXXXXXX X XXXXXX XXXXXXXXXX XXXXXXXX XXX XXXXX XXXXXX XXX X 
                            XX
                            XXXXXX X
                                XXXXXXXX XXXXX
                                XXXXX X gettext(u'Distribuição do Uso de Disco') XX
                                XXXXXX XXXXXXXXXX
                                XXXXXXXX X XXXX XXX XXXXXXX XX XX
                                XXXXX X XXXXX XXX XXXXXXX XXXXXXXX X
                            XX
                            XXXXXXXX X
                                XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX
                                XXXXXXXXXX X
                                    XXXXXX XXXXXXXXXXXXXXXXX X
                                        XXX XXXXX X XXXXXXXXXXXXX XX XXX
                                        XX XXXXXXX X XXXXX XX XX XX X
                                        XX XXXXXXXXXXXXXXX XXX XXXXX X
                                            XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X X XXXX
                                        X
                                        XXXXXX XXXXXX
                                    X
                                X
                            X
                        XX
                        XXXXXXX XXXXX
                    X
                XXX
            X XXXX XX XXXXXXXXXXXXX X
                XX XX XXX XX XXXX XX XXXX X XX XXXXX XXX XXXX XX XXX XXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX X
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX gettext(u'Dados de uso do disco não suficientes ou zerados para gerar gráfico.') XXXXXX
                X
            X
        XXX
    XXXXXXXXX
BBBBBBBB