BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBB

BBBBB BBBBB gettext(u'Resultados da busca por')  XXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX
            BB BBBBBBBBBBBB
                 gettext(u'Resultados para')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            BBBB
                 gettext(u'Por favor, digite um termo para buscar') 
            BBBBB
        XXXXX
    XXXXXX

    BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBBBB
                BBBB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBBBBBB BBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBB
                                BBBBB BBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBB
                                XXXX XXXXXX XXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                BBBBBBB
            BBBBBB
        XXXXXX

        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXX gettext(u'Anterior') XXXX
                BBBBB

                XXXXX XXXXXXXXXXXXXXXX
                     gettext(u'Página')    gettext(u'de')  
                XXXXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXX gettext(u'Próxima') XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXFFFFFFFFFXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        BBBBB

    BBBB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX XXX XX XXXXX XXXXXXXXXXXXXX
        XXXXXX
    BBBBB
XXXXXX
BBBBBBBB