# Generated by Django 5.1.8 on 2025-05-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página Inicial'},
        ),
    ]
