BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Upload de PDF(s) para %(title)s') SSSSSS SS SSSSSS SSSS SSSSSSSSSBBBBBBBB

BBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX gettext(u'Você está upando capítulos para a obra:') XXXX
                XXX XXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXX
                            XX XXXXXXXXXXXXXXXXXX XX XX XXXX XXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXX
                        XXXXX
                    XXXXX
                    
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Upar e Dividir PDF(s)') 
                    XXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB