BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
        X
        XXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXX XXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        XXXXXX XXXXX X
            XXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXX X XXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX X X XXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXX XX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXX XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        XXXXXX XXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXX
            XXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXX XX
        X
        XXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXX XXXXX XX
            XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X

        XX XXXXXXX XXXX XX XXXXXX XX XXXXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXX X
            XXXXXXXX XXXXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXX XXXXX X
            XXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XX XXX XX XXXXX XX XXXXXX XX XXX XX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXX XXXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
             gettext(u'\n            Faça upload de um arquivo .ZIP contendo múltiplos arquivos de capítulo (ex: .txt ou .md).\n            O sistema tentará extrair o número e o título do capítulo a partir dos nomes dos arquivos. Se os\n            arquivos dentro do ZIP forem PDFs, o sistema tentará extrair o texto deles e dividi-los em\n            capítulos baseado no padrão "Capítulo X: Nome do Capítulo". As tags de imagem customizadas\n            <code>[WAGTAIL_IMG_ID:identificador_da_imagem]</code> serão processadas.\n            ') 
            SSSS SSSSSS SS SS SSSSSSS SSSS SSSSSSSS SSSSSSSSS SSSSSSSS SS SSSSSSSS SSSS SSSS SS SSSSS
            S SSSSSSS SSSSSSS SSSSSSS S SSSSSS S S SSSSSS SS SSSSSSSS S SSSSSS SSS SSSSS SSS SSSSSSSSS SS SS
            SSSSSSSS SSSSSS SS SSS SSSSS SSSSS S SSSSSSS SSSSSSS SSSSSSS S SSSSS SSSSS S SSSSSSSSSS SS
            SSSSSSSSS SSSSSSS SS SSSSSS SSSSSSSSS SS SSSS SS SSSSSSSSSS SS SSSS SS SSSSSS SSSSSSSSSSSS
            SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSS SSSSSSSSSSSS
            
        XXXX

        BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    XXXBB BBBBBBBBBBBB XXXXXXXXXXXXXX XBBBBBX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBBBB
            XXXXX
        BBBBB

        XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB

            BB BBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXBBBBBBXXXXX
            BBBBB

            XXX XXXXXXXXXXXXXXX
                BBB BBBBB BB BBBB
                    XXX XXXXXXXXXXXX XXXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB BB BBBBBBBBBBBBXXXXXBBBBBXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            
                            
                            BB BBBBBBBBBBBBBBBXX XXXXXXXXXXXXXFFFFXXXXBBBBB
                            BBB BBBBB BB BBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB
                        XXXXXX
                    XXXXX
                BBBBBB
            XXXXX

            XXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                BBBB BBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Upar e Processar ZIP') 
                            XXXXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                             gettext(u'Cancelar') 
                        XXXX
                    XXXXX
                XXXXX
            XXXXXXXXX
        XXXXXXX

        BB BBBBBBBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Resultados do Processamento do ZIP:') XXXXX
            XXXX
                BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB 
                    BB BBBBBBBBBBBBBBBB BB BBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBB BB BBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBB BB BBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                        XXXXFFFFFFFFFFFFFFFFFXXXXX 
                    BBBBB
                BBBBBB
            XXXXX
        XXXXXXXXXX
        BBBBB

    XXXXXX
BBBBBBBB