BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBB gettext(u'Upar Capítulos - Selecione a Novel') BBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXX X
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXX XX 
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXX XXXXXX
        X
        
        XX XXXXXX XXXX X XXXXXXXX XX
        XXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
        X

        XX XXXXX XXXX XXXXXX XXXX XXXXXXX X XXXXX XXXXX XX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXX 
            XXXXX XX
            XXXXXX XX
            XXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXX XX
            XXXXXXX XX
        X
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXX X X
            XXXXXXXX XXXXXX
            XXXXXXXX XXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXX XXXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
     gettext(u'Upar Capítulos - Selecione a Novel') 
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        BB BBB BBBBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXX gettext(u'Nenhuma novel encontrada. Por favor, crie uma novel primeiro.') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX gettext(u'Ir para Páginas') XXXX
            XXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBB BB BBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBB
                                XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXX
                                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                     ngettext(u'%(counter)s Capítulo', u'%(counter)s Capítulos', count) SSSSSSSSSSS SSSSSSSSPPPPPPPPPPP PPPPPPPPP
                                BBBBBBB
                            XXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXX XXXXX XXXXXXXXXX XXX X XXXXX XXXXX XXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                                XXXXXXXXXXXX XX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                                XXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
                                XXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                                XXXX
                            XXXXXX
                        XXXXXX

                    XXXXXX
                BBBBBB
            XXXXXX
        BBBBB
    XXXXXX

    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XX XXXXXXXXX XXX XXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
    XXX
    XXXXXXXXX
BBBBBBBB