BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
        X
        XXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXX XXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        XXXXXX XXXXX X
            XXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXXX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXX X XXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX X X XXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
        XXXXXXXXXX XX X
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X
        XXXXXX XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        XXXXXX XXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXX XXXXXX
        X

        XX XXXXXXX XXXX XX XXXXXX XX XXXXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXX X
            XXXXXXXX XXXXX XXXX XX XXXXXXX XXXXXX XXX XXXXXX XXXXXXX XX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX XX XXXX XX XXXXX XXXXXX XX XXXXXXX XX
            XXXXXXXXXXXX XXXX XX XXXX XX XXXXX XXXXXX XX
            XXXXXXXXXX XXXXXXX XX XXXXXXX XX XXXXX XXXXXX XX
            XXXXXXXXXXXX XXXX XX XXXXXX XX XXXXX XXXXXX XX
            XXXXXXXX XXXXXXXXXXXX XX XXXX XXXXXXX XXXXX X XXXXX XX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX XX XXXXX XX XXXXXXXXXXX XX
            XXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXX XXXXXXX XXXXX X
            XXXXXXXXXXXXX XXXXXX XX XXXXXX XXXXX XXXXX X XXXXX XX
            XXXXXX XXXXXX XX XXXXXXXX X XXXXXXX XX XXXXXXXXX XX XXXXX XX
            XXXXXXX XXXXXX XX XXXXXXXX X XXXXXX XX XXXXXXXXX XX XXXXX XX
            XX X XXXXX XXX XX XXXXXXX XXXXXXXXXX XX XXXXXX XX XXXXXXXXX X XXXXX XX XXX XX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XX XXX XX XXXXX XXXXXXXX XX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXX X XXXXX XXXX XXXXXX XX
        X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXXXXX XX XXXXX XX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXXX XX
        X

        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
         XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    XXXBB BBBBBBBBBBBB XXXXXXXXXXXXXX XBBBBBX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBBBB
            XXXXX
        BBBBB

        XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB

            BB BBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXXXXXXXX
                    BBBBBB
                XXXXX
            BBBBB

            XXX XXXXXXXXXXXXXXX
                BBB BBBBB BB BBBB
                    XXX XXXXXXXXXXXX XXXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB BB BBBBBBBBBBBBXXXXXBBBBBXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            
                            
                            BB BBBBBBBBBBBBBBB
                                XX XXXXXXXXXXXXXFFFFXXXX
                            BBBBB
                            BBB BBBBB BB BBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXX
                    XXXXX
                BBBBBB
            XXXXX

            XXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                BBBB BBBBBBBBBBB gettext(u'Adicionar Capítulo') 
                            XXXXXXXXX
                        XXXXXX
                    XXXXX
                   XXX XXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'Cancelar') 
    XXXX
XXXXX
                XXXXX
            XXXXXXXXX
        XXXXXXX
    XXXXXX
    
BBBBBBBB