# Generated by Django 5.2 on 2025-06-02 17:30

import django.db.models.deletion
import novels.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Gênero')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Será preenchido automaticamente se deixado em branco.', max_length=255, unique=True)),
                ('synopsis', models.TextField(verbose_name='Sinopse')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=novels.models.novel_cover_path, verbose_name='Imagem de Capa')),
                ('status', models.CharField(choices=[('DR', 'Rascunho'), ('PB', 'Publicada'), ('OG', 'Em Andamento'), ('CP', 'Concluída'), ('HT', 'Hiato'), ('CL', 'Cancelada')], default='DR', max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novels_authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('genres', models.ManyToManyField(blank=True, related_name='novels', to='novels.genre', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Novel',
                'verbose_name_plural': 'Novels',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Capítulo')),
                ('slug', models.SlugField(blank=True, help_text='Será preenchido automaticamente se deixado em branco.', max_length=255)),
                ('chapter_number', models.PositiveIntegerField(help_text='Usado para ordenação.', verbose_name='Número do Capítulo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='Novel')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['novel', 'chapter_number'],
                'unique_together': {('novel', 'chapter_number'), ('novel', 'slug')},
            },
        ),
    ]
