# Generated by Django 5.2 on 2025-06-02 17:38

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelChapterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('chapter_number_display', models.CharField(help_text="Ex: 'Capítulo 1', 'Prólogo', 'Volume 2 - Capítulo 5'", max_length=100, verbose_name='Número/Título do Capítulo (Exibição)')),
                ('content', wagtail.fields.RichTextField(verbose_name='Conteúdo do Capítulo')),
                ('release_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Página de Capítulo de Novel',
                'verbose_name_plural': 'Páginas de Capítulo de Novel',
                'ordering': ['path'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='novel',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='author',
        ),
        migrations.CreateModel(
            name='NovelGenreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Gênero da Novel',
                'verbose_name_plural': 'Gêneros da Novel',
            },
        ),
        migrations.CreateModel(
            name='NovelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Autor(es)')),
                ('synopsis', wagtail.fields.RichTextField(blank=True, verbose_name='Sinopse')),
                ('status', models.CharField(choices=[('DR', 'Rascunho'), ('OG', 'Em Andamento'), ('CP', 'Concluída'), ('HT', 'Hiato'), ('CL', 'Cancelada')], default='OG', max_length=2, verbose_name='Status')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa da Novel')),
                ('genres', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='novels.NovelGenreTag', to='taggit.Tag', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Página de Novel',
                'verbose_name_plural': 'Páginas de Novel',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='novelgenretag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_tags', to='novels.novelpage'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
    ]
