# Generated by Django 5.2 on 2025-06-03 19:25

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novelchapterpage_remove_novel_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapterpage',
            options={'ordering': ['chapter_number_sortable'], 'verbose_name': 'Página de Capítulo de Novel', 'verbose_name_plural': 'Páginas de Capítulo de Novel'},
        ),
        migrations.RemoveField(
            model_name='novelchapterpage',
            name='chapter_number_display',
        ),
        migrations.RemoveField(
            model_name='novelchapterpage',
            name='content',
        ),
        migrations.AddField(
            model_name='novelchapterpage',
            name='chapter_display_title',
            field=models.CharField(default='', help_text="Ex: 'Capítulo 1: O Despertar', 'Prólogo'", max_length=255, verbose_name='Título de Exibição do Capítulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novelchapterpage',
            name='chapter_number_sortable',
            field=models.FloatField(default=1.0, help_text='Ex: 1.0, 1.5, 2.0. Usado para ordenar capítulos.', verbose_name='Número para Ordenação'),
        ),
        migrations.AddField(
            model_name='novelchapterpage',
            name='main_content',
            field=wagtail.fields.RichTextField(default='', verbose_name='Conteúdo Principal do Capítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novelchapterpage',
            name='release_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Publicação/Lançamento'),
        ),
    ]
