# Generated by Django 5.2 on 2025-06-03 19:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_alter_novelchapterpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapterpage',
            name='chapter_display_title',
            field=models.CharField(default='', help_text="Ex: 'Capítulo 1: O Despertar', 'Prólogo'", max_length=255, verbose_name='Título de Exibição do Capítulo'),
        ),
        migrations.AlterField(
            model_name='novelchapterpage',
            name='chapter_number_sortable',
            field=models.FloatField(default=0.0, help_text='Ex: 1.0, 1.5, 2.0. Usado para ordenar capítulos.', verbose_name='Número para Ordenação'),
        ),
        migrations.AlterField(
            model_name='novelchapterpage',
            name='main_content',
            field=wagtail.fields.RichTextField(default='', verbose_name='Conteúdo Principal do Capítulo'),
        ),
    ]
