# Generated by Django 5.2 on 2025-06-09 03:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_novelchapterpage_chapter_display_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapterpage',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número de vezes que este capítulo foi visualizado.', verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='novelpage',
            name='discord_series_role_id',
            field=models.CharField(blank=True, help_text='Opcional. ID do cargo do Discord a ser mencionado quando novos capítulos desta obra forem lançados.', max_length=30, null=True, verbose_name='ID do Cargo no Discord (Notificações)'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Favoritado em')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='novels.novelpage', verbose_name='Novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-favorited_at'],
                'unique_together': {('user', 'novel')},
            },
        ),
    ]
