# Generated by Django 5.2 on 2025-06-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novelchapterpage_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapterpage',
            options={'ordering': ['-chapter_number_sortable'], 'verbose_name': 'Página de Capítulo de Novel', 'verbose_name_plural': 'Páginas de Capítulo de Novel'},
        ),
    ]
