# Generated by Django 5.2 on 2025-06-19 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_alter_novelchapterpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='novels.novelpage', verbose_name='Favorito'),
        ),
    ]
