BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBBBBB BBBBBB

BBBBB BBBBBBBB _("Upar Capítulos por Pastas") BBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XX X XXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXX XXXXXXXX XXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXXX XXX XXXXXX XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXX XXXXXXX X XXXX XXXX XXXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXX XXXXX XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX XXXXXXXXXX XX XXXXXXXXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXX XXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'1. Selecione a Obra') XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXX XXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXX XXXXXXXXX XXX XXXX XXXXXXXXXXXX
                                BBB BBBBB BB BBBBBBBBBBBBBBB
                                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                                BBBBBB
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXX

                XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'2. Arraste as Pastas dos Capítulos') XXXXX
                        XX XXXXXXXXXXXXX
                            XXXXXXX XXXX X XXXX XXXXXX XXX XX XXXX XXXXXXX XXXX XXXXX XXXX XXXXXXX XXXX XX XXXXXXXXX
                        XXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXX XX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Clique aqui ou arraste as pastas para esta área') 
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Sel. Todos') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Des. Todos') XXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXX
                
                 XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Processar Capítulos Selecionados') 
                    XXXXXXXXX
                XXXXX
            XXXXX
        XXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX gettext(u'Resultados do Processamento:') XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
    
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

            XXX XXXXXXXXXXXXXXXXXXXXX X XXX

            XXXXXXXX XXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
            X

            XX XXXXXXXXXXXXX X 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX 
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXX
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X 
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX

            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXX X XXX
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXXXXXXXXXXX XXX XX X
                    XXXXXXXXXXXXXXXXX
                    XXXXXXX
                X

                XXXXX XXXXXXXXXXXXX X XXX XXXXXX
                XXX XXXXXX XXXX XX XXXXXXXXXXX X
                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXX XXXX
                    X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                
                XXX XXXX XXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
                    XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXX XX XXX XXX XXX X
                        XXXXXXXXXXX X XXXXXXXXXXX
                    X

                    XX XXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XX
                    X
                X
                XXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
            X

            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXX XXXX X XXXXX
            X

            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX X XXXXXXXXX

                    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXX XXXX X XXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                    XXX

                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXX XX XXXXXXX

                        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX

                        XXXXXXXXXXXX X X
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                                    XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                                XXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                                XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXXXX
                        XX

                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XX X
                            XXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXX
                        XX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                        
                        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX X XXXXXXX XX X
                            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
                                XXXXX XXXXXX X XXX XXXXXXXXXXXXX
                                XXXXXXXXXXXXX X XXX XX X
                                    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                                XX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            X
                        XX
                        XXXXXXXXXXXXXXXXXXX
                    XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            X
            
            XXXXXXXXXXXXXXXXXXXX X XX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXXXXX X XX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXX XX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXXXXXXXXX X XXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX X XXXXXXX X

                XXXXX XXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX
                    X
                XXX

                XXX XXXXXX XXXX XX XXXXXXXXXXXXXX X
                    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XXXXX XXXXXXXX X XXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    X

                    XXX X
                        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XXXXXXX XXXXXXX
                            XXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXX XX
                            XXXXX XXXXXXXXX
                        XXX
                        XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X XXXX X
                            XXXXX XXX XXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXX
                        X
                    X XXXXX XXXXXXX X
                        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX

            XXXXXXXXXXXXXXXXXX 
        XXX
    XXXXXXXXX
BBBBBBBB