# Generated by Django 5.2 on 2025-06-19 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: VIP Mensal', max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(blank=True, help_text='Descreva os benefícios deste plano.', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor do plano em Reais. Use ponto como separador decimal, ex: 29.90', max_digits=10, verbose_name='Preço (R$)')),
                ('duracao_dias', models.PositiveIntegerField(help_text='Número de dias que a assinatura ficará ativa. Ex: 30 para mensal, 365 para anual.', verbose_name='Duração em Dias')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder este plano da página de assinaturas.', verbose_name='Plano Ativo')),
            ],
            options={
                'verbose_name': 'Plano VIP',
                'verbose_name_plural': 'Planos VIP',
                'ordering': ['preco'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(db_index=True, verbose_name='Data de Expiração')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_vip', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinantes', to='subscriptions.planovip', verbose_name='Plano Assinado')),
            ],
            options={
                'verbose_name': 'Assinatura de Usuário',
                'verbose_name_plural': 'Assinaturas de Usuários',
                'ordering': ['-data_fim'],
            },
        ),
    ]
