# Generated by Django 5.2 on 2025-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planovip',
            name='livepix_plan_id',
            field=models.CharField(blank=True, help_text='O ID do Plano correspondente criado no painel da LivePix (ex: plan_xxxx...).', max_length=100, null=True, verbose_name='LivePix Plan ID'),
        ),
    ]
