# Generated by Django 5.2 on 2025-06-20 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_planovip_livepix_plan_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livepix_reference', models.CharField(help_text='ID de referência retornado pela API da LivePix', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.planovip')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
