# Generated by Django 5.2 on 2025-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Pacote de 100 Moedas', max_length=100, verbose_name='Nome do Pacote')),
                ('description', models.TextField(blank=True, help_text='Opcional. Dê mais detalhes sobre o pacote.', verbose_name='Descrição')),
                ('amount', models.PositiveIntegerField(help_text='Quantas moedas o usuário receberá.', verbose_name='Quantidade de Moedas')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço em Reais (BRL). Use ponto como separador decimal, ex: 2.99', max_digits=10, verbose_name='Preço (R$)')),
                ('livepix_product_id', models.CharField(blank=True, help_text='O ID do produto ou da cobrança correspondente na LivePix.', max_length=100, null=True, verbose_name='LivePix Product ID (Opcional)')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para esconder este pacote da loja sem deletá-lo.', verbose_name='Ativo na Loja?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Pacotes com números menores aparecem primeiro na loja.', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Pacote de Moedas',
                'verbose_name_plural': 'Pacotes de Moedas',
                'ordering': ['order', 'price'],
            },
        ),
    ]
