# Generated by Django 5.2 on 2025-07-17 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_coinpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='Saldo de Moedas')),
                ('discord_id', models.CharField(blank=True, help_text='ID do usuário no Discord para integração com o Bot.', max_length=100, null=True, verbose_name='ID do Discord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Assinante',
                'verbose_name_plural': 'Perfis de Assinantes',
            },
        ),
    ]
