# Generated by Django 5.2 on 2025-07-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='pacote_moedas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.coinpackage'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.planovip'),
        ),
    ]
