# Generated by Django 5.2 on 2025-08-05 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_transacao_pacote_moedas_alter_transacao_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpackage',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço em Dólares Americanos para o PayPal. Ex: 0.99', max_digits=10, null=True, verbose_name='Preço (USD)'),
        ),
        migrations.AddField(
            model_name='planovip',
            name='preco_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do plano em Dólares Americanos para o PayPal. Ex: 5.99', max_digits=10, null=True, verbose_name='Preço (USD)'),
        ),
        migrations.CreateModel(
            name='PaypalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da Fatura')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (USD)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Pagamento Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Transação PayPal')),
                ('coin_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.coinpackage', verbose_name='Pacote de Moedas')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.planovip', verbose_name='Plano VIP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido PayPal',
                'verbose_name_plural': 'Pedidos PayPal',
                'ordering': ['-created_at'],
            },
        ),
    ]
