# Generated by Django 5.2 on 2025-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_coinpackage_price_usd_planovip_preco_usd_paypalorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpackage',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço em Dólares para o PayPal. Ex: 0.99', max_digits=10, null=True, verbose_name='Preço (USD)'),
        ),
        migrations.AlterField(
            model_name='planovip',
            name='preco_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do plano em Dólares para o PayPal. Ex: 5.99', max_digits=10, null=True, verbose_name='Preço (USD)'),
        ),
    ]
