# Generated by Django 5.2 on 2025-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_coinpackage_price_usd_alter_planovip_preco_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planovip',
            options={'ordering': ['price'], 'verbose_name': 'Plano VIP', 'verbose_name_plural': 'Planos VIP'},
        ),
        migrations.RemoveField(
            model_name='coinpackage',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='planovip',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='planovip',
            name='preco_usd',
        ),
        migrations.AddField(
            model_name='paypalorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planovip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do plano. A moeda (R$ ou US$) será definida nas Configurações Globais do site.', max_digits=10, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Valor do pacote. A moeda (R$ ou US$) será definida nas Configurações Globais do site.', max_digits=10, verbose_name='Preço'),
        ),
    ]
