BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Erro no Servidor') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX gettext(u'Erro Interno no Servidor') XXXXX
    XX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXX
         gettext(u'Desculpe, algo deu errado do nosso lado. Nossa equipe técnica já foi notificada sobre o problema.') 
    XXXX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Voltar para a Página Inicial') 
    XXXX
XXXXXX

XXXXXXX
    XX XXXXXXX XXX X XXXXXXXX XX XXXX XXXXX XXX XXXXXXXXXXXX XX XXXX XX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX
BBBBBBBB BBBBBBB