BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXFFFFFFFFFFFFFFFXX
XXXXXX	
        XXXX XXXXXX XXX XXXXXXXXX XXX
    XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXX XXXXXXXX

    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB X FFFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBXXXXXXXX
    
    XXXX XXXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBBBB
        XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX
    BBBBB

    XXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XXXX XXXXXXXXX X XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXX XX XXX XXXXX XXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
            XXXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFX
        X
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
        X
        X X XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX X
    XXXXXXXX

    XXXX XXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XX XXXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX

    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX

XXXXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBXX

    BBBBB BBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBB
    BBBBBBBB

    XXXXXX
        BBBBB BBBBBBBBBBBBBBB
    XXXXXXX

    BBBBB BBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBB
    BBBBBBBB
    
    XXXX XXXXXXX XX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXX XXXXXXXX X XXXXXXXXXXXX XX XXXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBB BBB BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB BBB BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB BBB BB BBBBBBBBBBBB
        BB BBB BBBBBBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            FFFF
            FFFF
            FFFF
            FFFF
            FFFF
            FFFF
            FFFF
            FFFF
        BBBBB
    BBBBB

    XXXX XXXXXXXXX X XX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBBBBB
    XXXXXXXX
    XX XXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXX X XXXX XXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                X
            XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXX XXXX XXX X
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
                XX XXXXXXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                X
            XXX
        X

        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXX X XXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXX X XXXXXXX
            XXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX X XXXXX XX XX X
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                    XXXXXXX
                X
                XXX X
                    XXXXX XXXXXXXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX X XXXXX XXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX X
                    XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX X XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXX X X
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                    X
                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            XX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            XXX
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
                XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                X
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                X
            XXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXX
    BBBBBBBB
XXXXXXX
XXXXXXX