BBBB BBBBBBBB BBBBBB

BB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXX XXXXXXXXXXXXX
            BBBB
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                    
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
                            BB BBBBBBBBBBBBBBBBXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBBBBB
                            
                        XXXXXXX
                    BBBBBB

                    XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXX
                    BBBB
                        FFFFFFFFFFFF
                    BBBBB
                    
                    BB BBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXX
                        XXXXXX
                    BBBBB
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    
                    BB BBBB BB BBBBBBBBBBBB BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BB BBBB BB BBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                            XXXX
                                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX
                            XXXXX
                        XXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBBBB
    XXXXXX

    BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BBBBBBBBB BBBBBBBBB
            BBBBB
        BBBBBB
    XXXXXX
    BBBBB
XXXXXX
BBBBB