BBBB BBBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BXXXXXXXXXXBBBBXXXXXXXXXXXBBBBBXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX 
            
            BB BBBBBBBBBBBBBBBBBBBBBBBBB B B
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXX XXXXXXXXX XX XXX XXXXXXXXXXX
                        XXXXXXXFFFFFFFFF XXXXXXXXXXXXX
                    XXXX
                BBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXX XXXXX
                    XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
        BBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXX
            XXXXXX
        BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBB
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXX XXXX X XXXXXXXXXXXXX
            XXXXXX
        BBBBBB
    XXXXXX

XXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX          XXXXXX XXXXX X XXXXXXXXX XX XXXXXXXXXXXXXX         XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X XXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXX

            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXX X XXXXXXXX

            XX XXXXXXXXXXX XX XXXXXXXXXXX X
                XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
                    XXXXXXX XXXXXXX
                    XXXXXXXX X
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XX X
                    XX XXXXXXXXXXXX XXX XXXXX X
                        XXXXXXXXXXXXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXX
            X
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        X

        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X XXXXXXXX
                XX XXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X
            XXXXXXX
        X

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            BB BBB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXX
            BBBBB

            XX XXXXXXXXXXXX X
                XXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXX XXXXXXXXXX X XXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXX XX X
                XX XXXXXXXXXXXX XXX XXXXX X
                    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX

                    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX X
                        XX XXXXXXXXX XXX XXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X XXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        X
                    X
                X XXXX X
                    XXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXX XX XXXXXXXXX XXX XXXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXX XXXXXXX
                XXXXXXXXXXXXXX XX XXXX XX XXXXXXXX XXXXX XXXXXXXXXXXXX
            XXX
        X
    XXX
XXX
XXXXXXXXX