XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
BBBB BBBBBBBBBBBBBBBBB

XXXXX
    XXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXX XXX XXXX XXXXXXX X XXXXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
        BB BBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        BBBBB

        XXXX XXXXXXXXX X XXXXX XX XXXXX XXXXXXXXX XXX XX XXXXXXX XX XXXXXX XXXXX XXX
        FFFFFFFFFFFFFFF

        XXXX XXXXX XX XXXXX XXX XXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXX XXXXXXXXX XXXXX XXXX XXXXXX XXXXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXX
                XXXX X XXXXX XX XXXXXXX XXXX XXXXXXX X XXXXX XXXXX X X XXX X XXXXXX XXX
                XXXX X XXXXXXXXXX XXXXX XXXXX XXXXXX XX XX XXXXXXXXXXXXXXXX XXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXX XXXXXXXX XXXXX XX XXXXXXX X XXXXX XX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX X XXXXXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXX XXXX XXXXXXXX XXXX XXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX          XXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXX
XX XXXXXXX XXX X XXXXXX XXXX XXXXXXXXX XXXXXX XXX XXXX XXXXX XXX X XXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXX
XX XXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXX
        XXXXX XXXX X XXXXXXXXXXXXXXX
        
        XX XXXXXX X XX XXXXX XX XXXXXXXXXX XXXX XXXXXX XX XX XXXXXXX X XXXXXX XX XX XX XXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX

        XX XXXXXX X
            XXXXX XXXXXX X XXX XXXXXXXXXXXXX

            XXXXXXXXXXXXX X XXXXXXXXXXX X
                XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX X XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXXX X XXXXXXXXX XX XXXXX XXX X XXXXX XXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXX
                
                XXXXXXXXXXXXXXXXX X XXXXXXXXXX X
                    XXXXXXXXXXX X XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                XX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X
X
XXXXXXXXX